In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from collections import Counter

from itertools import *

import json
import os
import time
import sys
import xmltodict
from datetime import datetime


PATH = "/Users/alexandrarottenkolber/Documents/02_Hertie_School/Master thesis/Master_Thesis_Hertie/data_analysis/01_data/Plenarprotokolle/"

In [488]:
with open(PATH + 'processed/id2speech_concat_POSTag_inshape.txt', 'r') as infile:
    id2rede_12_19 = json.load(infile)
infile.close()

In [561]:
ID_and_names_from_Wiki = pd.read_csv(PATH + 'processed/ID_and_names_from_Wiki.csv')
ID_and_names_from_Wiki.head()

     pageid wikidataid           name surname_lower forename_lower
0   1713670     Q77685    Özcan Mutlu         mutlu          özcan
1  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
2  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
3  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
4  10062062  Q40998599  Zaklin Nastic        nastic         zaklin

In [490]:
names_wiki = ID_and_names_from_Wiki["name"]
len(names_wiki)

2358

In [491]:
politicians_with_noID = []
for speech in id2rede_12_19.keys():
    if id2rede_12_19[speech]['politicianId'] == "-1": 
        name = id2rede_12_19[speech]['firstName'] + " " + id2rede_12_19[speech]['lastName']
        politicians_with_noID.append(name)

In [492]:
unique_names = pd.Series(politicians_with_noID).unique()

In [493]:
len(unique_names), len(politicians_with_noID)

(559, 2366)

In [494]:
flagged_speeches = []
names = []

name2newID = {}

id_counter = 100

PolID2info = {}
for speech in id2rede_12_19.keys():
    temp_dic = {}
    
    if id2rede_12_19[speech]['politicianId'] != "-1":

        politicianId = id2rede_12_19[speech]['politicianId']
        temp_dic['lastName'] = id2rede_12_19[speech]['lastName']
        temp_dic['firstName'] = id2rede_12_19[speech]['firstName']
        temp_dic['positionLong'] = id2rede_12_19[speech]['positionLong']
        temp_dic['positionShort'] = id2rede_12_19[speech]['positionShort']

        PolID2info[politicianId] = temp_dic
        
    elif id2rede_12_19[speech]['politicianId'] == "-1":
        
        name = id2rede_12_19[speech]['firstName'] + " " + id2rede_12_19[speech]['lastName']
        #names.append(name)
        
        intermed_dic = {}
        
        intermed_dic["new_ID"] = id_counter
        intermed_dic["speech"] = speech
        
        name2newID[name] = intermed_dic
        id_counter += 1
        
    else: 
        flagged_speeches.append(speech)

In [495]:
len(name2newID)

559

In [496]:
name2newID['Hans-Werner Müller'].keys()

dict_keys(['new_ID', 'speech'])

In [497]:
for fullname in name2newID.keys():    
    temp_dic = {}
    
    politicianId = name2newID[fullname]['new_ID']
    speech = name2newID[fullname]['speech']
    
    temp_dic['lastName'] = id2rede_12_19[speech]['lastName']
    temp_dic['firstName'] = id2rede_12_19[speech]['firstName']
    temp_dic['positionLong'] = id2rede_12_19[speech]['positionLong']
    temp_dic['positionShort'] = id2rede_12_19[speech]['positionShort']

    PolID2info[politicianId] = temp_dic

In [498]:
len(PolID2info), len(flagged_speeches), len(names) # 4438 len(flagged_speeches)

(2631, 0, 0)

In [499]:
len(PolID2info), len(flagged_speeches), len(names) # 4438 len(flagged_speeches)

(2631, 0, 0)

In [500]:
# Read in data

with open(PATH + 'processed/key2Party.txt', 'r') as infile:
    key2Party = json.load(infile)
infile.close()

In [501]:
for PolID in PolID2info.keys(): 
    for key in key2Party.keys(): 
        if (PolID2info[PolID]["lastName"].lower() == key2Party[key]["NACHNAME"].lower()) & (PolID2info[PolID]["firstName"].lower() == key2Party[key]["VORNAME"].lower()):
            PolID2info[PolID]["PARTY"] = key2Party[key]['PARTY']
            PolID2info[PolID]["WPs"] = key2Party[key]["WPs"]    
            PolID2info[PolID]["BORN"] = key2Party[key]["BORN"]

In [502]:
len(PolID2info)

2631

with open(PATH + 'processed/PolID2info_unique_IDs.txt', 'w') as outfile: 
    json.dump(PolID2info, outfile) 
outfile.close()

In [503]:
PolID2info_df = pd.DataFrame.from_dict(PolID2info).T.reset_index().rename(columns = {"index": "politicianID"})
PolID2info_df.head()

,politicianID,lastName,firstName,positionLong,positionShort,PARTY,WPs,BORN
0,11000246,Brandt,Willy,NA,Member of Parliament,SPD,"[1, 2, 4, 6, 7, 10, 8, 9, 11, 12]",18.12.1913
1,11002287,Süssmuth,Rita,NA,Member of Parliament,CDU,"[11, 12, 13, 14]",17.02.1937
2,11002354,Ullmann,Wolfgang,NA,Member of Parliament,BÜNDNIS 90/DIE GRÜNEN,"[11, 12]",18.08.1929
3,11000418,dregger,alfred,NA,Member of Parliament,CDU,"[7, 8, 9, 10, 11, 12, 13]",10.12.1920
4,11000891,heuer,uwe-jens,NA,Member of Parliament,PDS,"[11, 12, 13]",11.07.1927

In [504]:
PolID2info_df.to_csv(PATH + 'processed/PolIDtoInfo_df_uniqueIDs.csv')

In [505]:
name2newID['Ursula Seiler-Albring'].keys()

dict_keys(['new_ID', 'speech'])

In [506]:
id2rede_12_19['471974'].keys()

dict_keys(['concatSpeech', 'name', 'date', 'data_ready', 'electoralTerm', 'firstName', 'lastName', 'politicianId', 'positionShort', 'positionLong', 'date_control', 'timestamp'])

In [573]:
for key in id2rede_12_19.keys(): 
    
    name = id2rede_12_19[key]['firstName'] + " " + id2rede_12_19[key]['lastName']
    
    if (name in name2newID.keys()) & (id2rede_12_19[key]['politicianId'] == "-1"):
        id2rede_12_19[key]['politicianId'] = name2newID[name]["new_ID"]

In [574]:
for key in id2rede_12_19.keys(): 
    if id2rede_12_19[key]['politicianId'] == "-1": 
        print(key)

In [833]:
PolID2SpeechID = {}
for key in id2rede_12_19.keys(): 
    ID = id2rede_12_19[key]['politicianId']
    PolID2SpeechID[str(ID)] = {}
    PolID2SpeechID[str(ID)]["speeches"] = []
    
for key in id2rede_12_19.keys(): 
    ID = id2rede_12_19[key]['politicianId']
    PolID2SpeechID[str(ID)]["speeches"].append(key)
    PolID2SpeechID[str(ID)]["firstName"] = id2rede_12_19[key]['firstName']
    PolID2SpeechID[str(ID)]["lastName"] = id2rede_12_19[key]['lastName']

In [834]:
len(PolID2SpeechID)

2631

In [806]:
with open(PATH + 'processed/PolID2SpeechID.txt', 'w') as outfile: 
    json.dump(PolID2SpeechID, outfile) 
outfile.close()

In [835]:
PolID2SpeechID_df = pd.DataFrame.from_dict(PolID2SpeechID).T.reset_index().rename(columns = {"index": "politicianID"})
PolID2SpeechID_df.head()

,politicianID,speeches,firstName,lastName
0,11000246,"[471526, 479132, 489844]",Willy,Brandt
1,11002287,"[471554, 471574, 471612, 471651, 471680, 47168...",Rita,Süssmuth
2,11002354,"[471532, 471825, 471980, 472676, 473851, 47411...",Wolfgang,Ullmann
3,11000418,"[471527, 471596, 471692, 473651, 479473, 50886...",alfred,dregger
4,11000891,"[471536, 471967, 472560, 473468, 473996, 47411...",uwe-jens,heuer

In [768]:
PolID2SpeechID_df.to_csv(PATH + 'processed/PolID2SpeechID_df.csv')

### Joining datasets together

In [2]:
PolID2SpeechID_df = pd.read_csv(PATH + 'processed/PolID2SpeechID_df.csv').reset_index().drop(columns = ["index", "Unnamed: 0"])
PolID2SpeechID_df.head()

,politicianID,speeches,firstName,lastName
0,11000246,"['471526', '479132', '489844']",Willy,Brandt
1,11002287,"['471554', '471574', '471612', '471651', '4716...",Rita,Süssmuth
2,11002354,"['471532', '471825', '471980', '472676', '4738...",Wolfgang,Ullmann
3,11000418,"['471527', '471596', '471692', '473651', '4794...",alfred,dregger
4,11000891,"['471536', '471967', '472560', '473468', '4739...",uwe-jens,heuer

In [3]:
ID_and_names_from_Wiki = pd.read_csv(PATH + 'processed/ID_and_names_from_Wiki.csv')
ID_and_names_from_Wiki.head()

     pageid wikidataid           name surname_lower forename_lower
0   1713670     Q77685    Özcan Mutlu         mutlu          özcan
1  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
2  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
3  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
4  10062062  Q40998599  Zaklin Nastic        nastic         zaklin

In [18]:
PolID2SpeechID_df["firstName"] = PolID2SpeechID_df["firstName"].map(lambda x: str(x))

In [19]:
PolID2SpeechID_df["surname_lower"] = PolID2SpeechID_df["lastName"].map(lambda x: x.lower())
PolID2SpeechID_df["forename_lower"] = PolID2SpeechID_df["firstName"].map(lambda x: x.lower())
PolID2SpeechID_df["name"] = PolID2SpeechID_df["forename_lower"] + " " + PolID2SpeechID_df["surname_lower"]

In [839]:
#PolID2SpeechID_df[PolID2SpeechID_df["firstName"].isna() == True]

In [23]:
PolID2SpeechID_df.head()

,politicianID,speeches,firstName,lastName,surname_lower,forename_lower,name
0,11000246,"['471526', '479132', '489844']",Willy,Brandt,brandt,willy,willy brandt
1,11002287,"['471554', '471574', '471612', '471651', '4716...",Rita,Süssmuth,süssmuth,rita,rita süssmuth
2,11002354,"['471532', '471825', '471980', '472676', '4738...",Wolfgang,Ullmann,ullmann,wolfgang,wolfgang ullmann
3,11000418,"['471527', '471596', '471692', '473651', '4794...",alfred,dregger,dregger,alfred,alfred dregger
4,11000891,"['471536', '471967', '472560', '473468', '4739...",uwe-jens,heuer,heuer,uwe-jens,uwe-jens heuer

In [24]:
ID_and_names_from_Wiki.head()

     pageid wikidataid           name surname_lower forename_lower
0   1713670     Q77685    Özcan Mutlu         mutlu          özcan
1  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
2  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
3  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
4  10062062  Q40998599  Zaklin Nastic        nastic         zaklin

In [30]:
# correction of PolID2SpeechID_df


name_mapping_dic = {'jörg ganschow' : 'Jörg Wolfgang Ganschow',
 ' gysi' : 'Gregor Gysi',
 'vera lengsfeld' : 'Vera Lengsfeld',
 'jürgen w möllemann': 'Jürgen Möllemann',
 'irmgard schwaetzer': 'Irmgard Adam-Schwaetzer',
 ' schmidt': np.nan,
 'andrea gysi': 'Andrea Gysi',
 'harald b schäfer': 'Harald B. Schäfer',
 'gerhart rudolf baum': 'Gerhart Baum',
 'margot renesse': 'Margot von Renesse',
 'christina schenk': np.nan,
 ' bläss': 'Petra Bläss',
 'joachim graf schönburg-glauchau': 'Joachim Graf von Schönburg-Glauchau',
 ' wimmer': np.nan,
 ' schäfer': np.nan,
 'peter w reuschenbach': 'Peter Reuschenbach',
 'de maizi re': 'Thomas de Maiziere',
 ' heimrich': np.nan,
 'wolfgang stetten': 'Wolfgang von Stetten',
 'klein zur wahl des g- -gremiums': np.nan,
 'ku an sagt': np.nan,
 'tudjman sagt': np.nan,
 'teichman logischen': 'Cornelia von Teichman und Logischen',
 'reinhard schorlemer': 'Reinhard von Schorlemer',
 'heinrich l kolb': 'Heinrich Leonhard Kolb',
 'kohl erklärt': 'Helmut Kohl',
 ' stavenhagen': 'Lutz Stavenhagen',
 'lilo blunck': 'Lieselott Blunck',
 'susanne jaffke-witt': 'Susanne Jaffke',
 'kurt j rossmanith': 'Kurt Rossmanith',
 ' blank': np.nan,
 'hans with': 'Hans de With',
 'hans h gattermann': 'Hans H. Gattermann',
 'joachim poss': np.nan,
 'helmut kohl gen': 'Helmut Kohl',
 'gerhard o pfeffermann': 'Gerhard O. Pfeffermann',
 'michael schmude': 'Michael von Schmude',
 'uta titze': 'Uta Titze-Stecher',
 'lutz g stavenhagen': 'Lutz Stavenhagen',
 'sabine bergmann-pohl parl': 'Sabine Bergmann-Pohl',
 'ferdi tillmann': 'Ferdinand Tillmann',
 'gunter weissgerber': 'Gunter Weißgerber',
 'peter patema': 'Peter Paterna',
 'klaus w lippold': 'Klaus Lippold',
 'heinz werner hübner': 'Heinz Hübner',
 'bush sagt sich': np.nan,
 'dorle marx': 'Dorothea Marx',
 'bitte schön roswitha verhülsdonk': 'Roswitha Verhülsdonk',
 'jörg essen': 'Jörg van Essen',
 'herbert meissner': 'Herbert Meißner',
 'erich g fritz': 'Erich G. Fritz',
 'erika steinbach': 'Erika Steinbach-Hermann',
 'rita süssmuth überweisungsvorschlag': 'Rita Süssmuth',
 'detlev larcher': 'Detlev von Larcher',
 'paul k friedhoff': 'Paul Friedhoff',
 'gisela hilbrecht': np.nan,
 'rostock-laage hans georg wagner': 'Hans Georg Wagner',
 'peter h carstensen': 'Peter Harry Carstensen',
 'werner h skowron': 'Werner Skowron',
 'christel riemann-hanewinckel': 'Christel Hanewinckel',
 'alois graf waldburg-zeil': np.nan,
 'barbara höii': 'Barbara Höll',
 'werner tegtmeier': np.nan,
 'herr staatssekretär werner tegtmeier': np.nan,
 'karl-hermann haack': 'Karl Hermann Haack',
 'cornelia teichman': np.nan,
 'brigitte schulte': np.nan,
 'lothar maizi re': np.nan,
 'rita süssmuth nennen': 'Rita Süssmuth',
 'r werner schuster': 'Werner Schuster',
 'lutz g stavenhagen': 'Lutz Stavenhagen',
 'kohl zum milliardenkredit lautet': 'Helmut Kohl',
 'jetzt erklärt walter jens': np.nan,
 'bitte herr staatsminister helmut schäfer': 'Helmut Schäfer',
 'herr staatsminister helmut schäfer': 'Helmut Schäfer',
 'staatsministerin seiler-albring ursula seiler-albring': 'Ursula Seiler-Albring',
 'karl h fell': 'Karl H. Fell',
 'kohl hat kürzlich ausgeführt': 'Helmut Kohl',
 'ursula schmidt': np.nan,
 'meine damen herren': np.nan,
 'hans klein konzernabschlußbefreiungsverordnung': 'Hans Klein',
 'franz kroppenstedt': np.nan,
 ' dieter-julius-cronenberg': 'Dieter-Julius Cronenberg',
 'staatsministerin bitte ursula seiler-albring': 'Ursula Seiler-Albring',
 'gernot eder': 'Gernot Erler',
 'helmuth becker berichterstattung': "Helmuth Becker",
 'bertold reinartz': 'Bertold Mathias Reinartz',
 ' klaus-dieter-feige': 'Klaus-Dieter Feige',
 'dieter-julius cronenberg berichterstattung': 'Dieter-Julius Cronenberg',
 'erich maass': 'Erich Maaß',
 'bitte staatsministerin ursula seiler-albring': 'Ursula Seiler-Albring',
 'bitte staatsminister ursula seiler-albring': 'Ursula Seiler-Albring',
 'helmut kohl tatsache ist': 'Helmut Kohl',
 'andreas bülow': 'Andreas von Bülow',
 'frerich görts': np.nan,
 'rita süssmuth berichterstattung': 'Rita Süssmuth',
 ' hans-günthertoetemeyer': 'Hans-Günther Toetemeyer',
 'hans schuster': 'Hans P. H. Schuster',
 'carl-detlev hammerstein': 'Carl-Detlev Freiherr von Hammerstein',
 'reinhard meyer bentrup': 'Reinhard Meyer zu Bentrup',
 'barbara hält': 'Barbara Höll',
 'wolfgang geldern': 'Wolfgang von Geldern',
 'renate schmidt berichterstattung': 'Renate Schmidt',
 'kohl folgendes versprechen ab': 'Helmut Kohl',
 'hans a engelhard': 'Hans A. Engelhard',
 'hans klein berichterstattung': 'Hans Klein',
 ' kreisky': np.nan,
 'helmut kohl gestern erneut bekräftigte': 'Helmut Kohl',
 'ulrich inner': 'Ulrich Irmer',
 'wolfgang gröbl part': 'Wolfgang Gröbl',
 'wolfgang gröbl parl': 'Wolfgang Gröbl',
 'hans klein überweisungsvorschlag': 'Hans Klein',
 'joseph-todor blank': 'Joseph-Theodor Blank',
 'fujimori gesagt': np.nan,
 'frerich görts': np.nan,
 'bitte herr staatsminister anton pfeifer': 'Anton Pfeifer',
 'bitte helmut schäfer': 'Helmut Schäfer',
 'hans klein tagesordnungspunkt': 'Hans Klein',
 'cristian schmidt': 'Christian Schmidt',
 'dieter würzen': np.nan,
 'helmut schmidt hat einmal gesagt': np.nan,
 'johannes vöcking': np.nan,
 'wilhelm knittel': np.nan,
 'helmut schmidt': np.nan,
 'roosevelt hat einmal formuliert': np.nan,
 'klein darauf hingewiesen': np.nan,
 'walter priesnitz': np.nan,
 'heinemann immer wieder mahnend vorhielten': np.nan,
 'staatsminister ursula seiler-albring': 'Ursula Seiler-Albring',
 'minister ursula seiler-albring': 'Ursula Seiler-Albring',
 'staatsministerin ursula seiler-albring': 'Ursula Seiler-Albringi',
 'bitte herr staatsminister bernd schmidbauer': 'Bernd Schmidbauer',
 'walesa wie folgt formuliert hat': np.nan,
 'helmut scholz': np.nan,
 'helmuth becker überweisungsvorschlag': 'Helmuth Becker',
 'baldur wagner': np.nan,
 'kohl stellt fest': 'Helmut Kohl',
 'renate schmidt überweisungsvorschlag': 'Renate Schmidt',
 'peter bläss': 'Petra Bläss',
 'reante schmidt': 'Renate Schmidt',
 'südkoreas fragte': np.nan,
 'herr staatsminister bernd schmidbauer': 'Bernd Schmidbauer',
 'dieter-julius cronenberg überweisungsvorschlag': 'Dieter-Julius Cronenberg',
 'kohl mehr noch': 'Helmut Kohl',
 'wighard härdtl': np.nan,
 'dietrich vogel': np.nan,
 'franz-josef feiter': np.nan,
 'wilhelm knittel': np.nan,
 'bitte herr staatssekretär clemens stroetmann': np.nan,
 'clemens stroetmann': np.nan,
 'walesa es unumwunden ausgesprochen': np.nan,
 'franz-josef feiter': np.nan,
 'herr staatssekretär clemens stroetmann': np.nan,
 'clemens stroetmann': np.nan,
 'wighard härdtl': np.nan,
 'hans klein rhythmus -': 'Hans Klein',
 'bitte staatsministerire ursula seiler-albring': 'Ursula Seiler-Albring',
 'gemot eder' : 'Gernot Erler',
 'dieter-julius cronenberg tagesordnungspunkt k' : 'Dieter-Julius Cronenberg',
 'dieter vogel' : np.nan,
 'helmuth becker tagesordnungspunkt e' : 'Helmuth Becker',
 'bitte sehr helmut schäfer' : np.nan,
 'jelzin in seiner rede sagt' : np.nan,
 'hans klein der text lautet' : 'Hans Klein',
 'roman herzog' : np.nan,
 'roman herzog ländern' : np.nan,
 'ursula seiler-aibring' : 'Ursula Seiler-Albring',
 'hans klein tagesordnungspunkt m' : 'Hans Klein',
 'helmut kohl hat daran erinnert' : 'Helmut Kohl',
 'heinrich graf einsiedel' : 'Heinrich Graf von Einsiedel',
 'joseph fischer' : np.nan,
 'marieluise beck' : np.nan,
 'kohl formulierte' : 'Helmut Kohl',
 'herr staatsminister werner hoyer' : 'Werner Hoyer',
 'norbert rängen' : 'Norbert Röttgen',
 ' hans-ulrich' : np.nan,
 'eckart klaeden' : 'Eckart von Klaeden',
 'heidi wright' : 'Heidemarie Wright',
 'antje vollmer berichterstattung' : 'Antje Vollmer',
 'havel zitieren' : np.nan,
 'havel hat folgendes erklärt' : np.nan,
 'hans-ulrich klose berichterstattung' : 'Hans-Ulrich Klose',
 'wolfgang llte' : 'Wolfgang Ilte',
 'dagmar g wöhrl' : 'Dagmar Wöhrl',
 'frage des abgeordneten wolfgang steiger' : np.nan,
 'bitte franz-josef feiter' : np.nan,
 'manfred overhaus' : np.nan,
 'r manfred overhaus' : np.nan,
 'kohl zugeschickt' : 'Helmut Kohl',
 'hans-ulrich klose tagesordnungspunkt' : 'Hans-Ulrich Klose',
 'reagan gesagt' : np.nan,
 ' carl-ludwig' : 'Carl-Ludwig Thiele',
 'karl jung' : np.nan,
 'chirac premierminister jupp einig' : np.nan,
 'antje vollmer überweisungsvorschlag' : 'Antje Vollmer',
 'petra blass' : 'Petra Bläss',
 'hans-ulrich klose zusatzpunkt' : 'Hans-Ulrich Klose',
 'adelheid tröscher' : 'Adelheid D. Tröscher',
 'heinz dieter essmann' : np.nan,
 'gottfried trager' : 'Gottfried Tröger',
 'karl jung' : np.nan,
 'wolfensohn u a' : 'Renate Schmidt',
 'antje vollmer tagesordnungspunkt' : 'Antje Vollmer',
 'jürgen stark' : np.nan,
 'bitte jürgen stark' : np.nan,
 'clinton hat recht gesagt' : np.nan,
 'izetbegovic gesagt hat ist richtig' : np.nan,
 'hans-ulrich klose überweisungsvorschlag' : 'Hans-Ulrich Klose',
 'bernd klaussner' : 'Bernd Klaußner',
 'bitte werner hoyer' : 'Werner Hoyer',
 'helmut schmidt ablösten sagten sie' : np.nan,
 'hans klein tue ich hiermit' : np.nan,
 'bitte herr staatssekretär helmut schäfer' : 'Helmut Schäfer',
 'burkhard hirsch richtigen' : 'Burkhard Hirsch',
 'antje vollmer sagt' : 'Antje Vollmer',
 'hans klein zusatzpunkt' : 'Hans Klein',
 'hans-friedrich ploetz' : np.nan,
 'bitte schön bernd schmidbauer' : 'Bernd Schmidbauer',
 'karl a lamers' : 'Karl A. Lamers',
 'hans-ulrich klose gesordnung folgendes mit' : 'Hans-Ulrich Klose',
 'hirsch hat mit recht gesagt' : np.nan,
 'kohl sagt' : 'Helmut Kohl',
 'herzog hingewiesen hat' : 'Gustav Herzog',
 'burkhard hirsch überweisungsvorschlag' : 'Burkhard Hirsch',
 'herr staatssekretär helmut schäfer' : 'Helmut Schäfer',
 'bitte schön helmut schäfer' : 'Helmut Schäfer',
 'peter hausmann' : np.nan,
 'walter hirrlinger fordert' : np.nan,
 'marielulse beck' : np.nan,
 'peter hausmann' : np.nan,
 'hans-ulrich klose wörtlich gesagt' : 'Hans-Ulrich Klose',
 'kiesinger vor dem hohen hause' : np.nan,
 'milosevi gerichtet' : np.nan,
 'mandela hat gesagt' : np.nan,
 'milo evi' : np.nan,
 'heinz-georg seifert' : np.nan,
 'bitte schön werner hoyer' : 'Werner Hoyer',
 'michaela geiger berichterstattung' : 'Michaela Geiger',
 'burkhard hirsch berichterstattung' : 'Burkhard Hirsch',
 'herzog stammt der satz' : np.nan,
 'bitte herr staatssekretär wilhelm hecker' : np.nan,
 'wilhelm hecker' : np.nan,
 'herr staatssekretär wilhelm hecker' : np.nan,
 'herr staatsminister bitte helmut schäfer' : 'Helmut Schäfer',
 'michaela geiger tagesordnungspunkt a' : 'Michaela Geiger',
 'herzog in straßburg gesagt hat' : np.nan,
 'michaela geiger zusatzpunkt' : 'Michaela Geiger',
 ' carl-ludwig-thiele' : 'Carl-Ludwig Thiele',
 'hans-ulrich klose gestimmt' : 'Hans-Ulrich Klose',
 'hans-ulrich klose tagesordnungspunkt u' : 'Hans-Ulrich Klose',
 'helmut kohl erstens' : 'Helmut Kohl',
 'herzog geprägt hat' : 'Gustav Herzog',
 'hans-ulrich klose abgegebene stimmen' : 'Hans-Ulrich Klose',
 'burkhard hirsch zusatzpunkt' : 'Burkhard Hirsch',
 'jelzin sagte ihm' : np.nan,
 'christa thoben' : np.nan,
 'michaela geiger überweisungsvorschlag' : 'Michaela Geiger',
 'milosevic muß wissen' : np.nan,
 'herzog gesagt hat' : np.nan,
 'herzog es meinte' : np.nan,
 'willi hausmann' : np.nan,
 'antje vollmer zusatzpunkt' : 'Antje Vollmer',
 'hans-ulrich klose tagesordnungspunkt i' : 'Hans-Ulrich Klose',
 'hans-ulrich klose tagesordnungspunkt q' : 'Hans-Ulrich Klose',
 'hans-ulrich klose tagesordnungspunkt o' : 'Hans-Ulrich Klose',
 'hans-ulrich klose tagesordnungspunkt x' : 'Hans-Ulrich Klose',
 'hans-ulrich klose zusatzpunkt a' : 'Hans-Ulrich Klose',
 'bodo hombach' : np.nan, 
 'werner müller' : "Hans-Werner Müller",
 'karl-heinz funke' : np.nan,
 'christine bergmann' : np.nan,
 'willy brandt gesagt' : np.nan,
 'schröder weiter steht da' : np.nan,
 'klaus wolfgang müller' : np.nan,
 'wolfgang gehrcke-reymann' : "Wolfgang Gehrcke",
 'ulla lötzer' : "Ursula Lötzer",
 'kohl nicht gegeben hätte' : np.nan,
 'schröder der bundeskanzler weiter' : np.nan,
 'ernst ulrich weizsäcker' : "Ernst Ulrich von Weizsäcker",
 'axel e fischer' : "Axel Fischer",
 'michael naumann' : np.nan,
 'klima sagt' : np.nan,
 'schröder übrigens' : np.nan,
 'ahtisaari die nachricht aus belgrad' : np.nan,
 'karl lamers -karl lamers' : "",
 'schröder auf' : np.nan,
 'schröder gesagt' : np.nan,
 'schröder klar sein' : np.nan,
 'annette fugmann-heesing' : np.nan,
 'roland koch' : np.nan,
 'johannes rau' : np.nan,
 'schröder sagen' : np.nan,
 'hoover erklärte' : np.nan,
 'eckart werthebach' : np.nan,
 'ren röspel' : "René Röspel",
 'uwe-karsten heye' : np.nan,
 'reinhard klimmt' : np.nan,
 'vizepräsidentin petra bläss' : "Petra Bläss",
 'gespräche über die frage' : np.nan,
 'schröder hätte ihnen gesagt' : np.nan,
 'cajus caesar' : "Cajus Julius Caesar",
 'kollegin - rita streb-hesse' : np.nan,
 'rainer baake' : np.nan,
 'schröder in dem er mitteilt' : np.nan,
 'hirrlinger sagt dazu' : np.nan,
 ' christaluft' : "Christa Luft",
 'grietje staffelt' : np.nan,
 'christoph stölzl' : np.nan,
 'willfried maier' : np.nan,
 'hartmuth wrocklage' : np.nan,
 'achim großmann parl staatssekretär beim bundesminister für verkehr bau- wohnungswesen' : "Achim Großmann",
 'erich stather' : np.nan,
 'peter haupt' : np.nan,
 'johannes rau schließen' : np.nan,
 'ihnen gesagt hätte' : np.nan,
 'schröder bekräftigt hat' : np.nan,
 'schröder in seiner regierungserklärung ausgeführt' : np.nan,
 ' santer' : np.nan,
 'erwin anton jordan' : np.nan,
 'schröder führte weiter aus' : np.nan,
 'julian nida-rümelin' : np.nan,
 'gerhard schröder gesagt' : np.nan,
 'gunter pleuger' : np.nan,
 'schröder wort gemeldet hat' : np.nan,
 'herr staatssekretär erich stather' : np.nan,
 'schröder knallhart gesagt' : np.nan,
 'peter kurth' : np.nan,
 'schröder hat recht' : np.nan,
 'mosdorf oder so wie jetzt' : np.nan,
 'rau hat gesagt' : np.nan,
 'bush sagte sie' : np.nan,
 ' hundt' : np.nan,
 'kohl dort heißt es' : np.nan,
 'ebtekar - deutlich geworden' : np.nan,
 'herr möllemann ist - steht' : np.nan,
 'schröder gesagt hat' : np.nan,
 'bush hat darüber gesprochen' : np.nan,
 'theodor heuss als er sagte' : np.nan,
 'helmut schmidt hat gesagt' : np.nan,
 'thomas flierl' : np.nan,
 'schröder gilt' : np.nan,
 'ronald b schill' : np.nan,
 'kohl sagte' : np.nan,
 'manfred stolpe' : np.nan,
 'wolfgang stolpe' : np.nan,
 'schröder vollmundig aufgestellte forderung' : np.nan,
 'silke stokar neuforn' : np.nan,
 'christina weiss' : np.nan,
 'helmut schmidt hat völlig recht' : np.nan,
 'cornelia mayer' : np.nan,
 'christian stetten' : np.nan,
 'dorothee bär' : np.nan,
 'karl-theodor guttenberg' : "Karl-Theodor zu Guttenberg",
 'karzai hat uns gesagt' : np.nan,
 'b la anda' : np.nan,
 'spd-mitglied roland schäfer' : np.nan,
 'chirac hat immer gesagt' : np.nan,
 'josef philip winkler' : "Josef Winkler",
 'wolfgang thierse berichterstattung' : "Wolfgang Thierse",
 'schröder unter anderem erklärt': np.nan,
 ' bundeskanzleramtes': np.nan,
 'hermann otto solms überweisungsvorschlag' : "Hermann Otto Solms",
 'klaus werner jonas' : "Klaus-Werner Jonas",
 'b la anda' : np.nan,
 'wolfgang thierse überweisungsvorschlag' : "Wolfgang Thierse",
 'gerhard schröder zentrale aussage war' : "Gerhard Schröder",
 'schröder äußerte sich dazu wörtlich' : np.nan,
 'braun hat gestern gesagt' : np.nan,
 'wolfgang böhmer' : np.nan,
 'schröder übrigens seinem vorgänger' : np.nan,
 'schröder verkündet dazu': np.nan,
 'roger kusch' : np.nan,
 'hermann otto solms berichterstattung': "Hermann Otto Solms",
 'professor hans-jörg jacobsen': np.nan,
 'ist das richtig kerstin müller': "Kerstin Müller",
 ' deutschland': np.nan,
 'hermann otto solms landwirtschaft': "Hermann Otto Solms",
 'norbert lammert berichterstattung': "Norbert Lammert",
 'harald wolf': np.nan,
 'elvira drobinski-weiss': "Elvira Drobinski-Weiß",
 'dieter althaus': np.nan,
 'professor horst köhler': np.nan,
 'gerhard schröder erwarten': "Gerhard Schröder",
 'recht hat': np.nan,
 'bush nimmt': np.nan,
 'kiesinger in einer regierungserklärung': np.nan,
 'herr koch-weser': np.nan,
 'eisenhower hat gesagt': np.nan,
 'schröder dem bosnischen ministerpräsidenten mitgeteilt': np.nan,
 'schröder wortwörtlich geantwortet': np.nan,
 'schröder soll geantwortet haben': np.nan,
 'schüssel erklärt mit stolz': np.nan,
 'staatsministerin christina weiss': np.nan,
 'köhler sagen': np.nan,
 'aus verantwortung für unser land': np.nan,
 'ziercke sagte in demselben interview': np.nan,
 'thumann hat festgestellt': np.nan,
 'israel besuchte sagte damals': np.nan,
 'schröder nur empfehlen': np.nan,
 'carl-eduard bismarck': "Carl-Eduard von Bismarck",
 'sie gefragt hat': np.nan,
 'köhler zitieren': np.nan,
 'ursula der leyen': "Ursula von der Leyen",
 'thomas maizi re': np.nan,
 'vizepräsident wolfgang thierse': "Wolfgang Thierse",
 'wolfgang neskovic': "Wolfgang Nešković",
 'merkel -': "Angela Merkel",
 'doroth e menzner': "Dorothée Menzner",
 'recht geben': np.nan,
 'sevim da delen': "Sevim Dağdelen",
 'heidrun bluhm-förster': "Heidrun Bluhm",
 'gerhard schröder hatte gesagt': "Gerhard Schröder",
 'hakki keskin': "Hakkı Keskin",
 'heuss hat einmal gesagt': np.nan,
 'angela merkel zitieren': np.nan,
 'max lehmer': "Maximilian Lehmer",
 'gerda hasselfeldt überweisungsvorschlag': "Gerda Hasselfeldt",
 'herr lämmel - andreas g lämmel': "Andreas Lämmel",
 'edmund peter geisen': "Edmund Geisen",
 'schröder der sagt': np.nan,
 'philipp missfelder': "Philipp Mißfelder",
  'bernd neumann die folgende antwort' : np.nan,
 'katrin göring-eckardt tagesordnungspunkt b': "Katrin Göring-Eckardt",
 'merkel gesagt hat': "Angela Merkel",
 'schröder schon früher sagte': np.nan,
 'wolfgang ne kovi': "Wolfgang Nešković",
 'klaus böger': np.nan,
 'norbert lammert überweisungsvorschlag': "Norbert Lammert",
 'mbeki sagt': np.nan,
 'petra pau tagesordnungspunkt': "Petra Pau",
 'merkel hat gesagt': np.nan,
 'angela merkel sagen': np.nan,
 'katrin göring-eckardt überweisungsvorschlag': "Katrin Göring-Eckardt",
 'katrin göring-eckardt tagesordnungspunkt f' : "Katrin Göring-Eckardt",
 'hien auf nachfrage': np.nan,
 'gerda hasselfeldt tagesordnungspunkt e' : "Gerda Hasselfeldt",
 'angela merkel enthalten' : "Angela Merkel",
 'gerda hasselfeldt tagesordnungspunkt i' : "Gerda Hasselfeldt",
 'inhalt der gesetzesänderungen ist'  : np.nan,
 'katrin lompscher'  : np.nan,
 'hans bernhard beus'  : np.nan,
 'horst köhler schließen'  : np.nan,
 'gerda hasselfeldt tagesordnungspunkt d' : "Gerda Hasselfeldt",
 'gerda hasselfeldt tagesordnungspunkt j' : "Gerda Hasselfeldt",
 'putin gerichtet sage ich'  : np.nan,
 'bitte gernot erler' : "Gernot Erler",
 'norbert lammert überwiesen' : "Norbert Lammert",
 'hüseyin-kenan aydin bundespräsident herzog' : "Hüseyin-Kenan Aydin",
 'herzog bundeskanzler kohl außenminister fischer' : "Helmut Kohl",
 'katrin göring-eckardt tagesordnungspunkt k' : "Katrin Göring-Eckardt",
 'katrin göring-eckardt zusatzpunkt' : "Katrin Göring-Eckardt",
 'katrin göring-eckardt berichterstattung' : "Katrin Göring-Eckardt",
 'angela merkel ich sage' : "Angela Merkel",
 'bush in tirana erklärt hat'  : np.nan,
 'katrin göring-eckardt tagesordnungspunkt o' : "Katrin Göring-Eckardt",
 'merkel sagte am november' : np.nan,
 'gerda hasselfeldt tagesordnungspunkt' : "Gerda Hasselfeldt",
 'gerda hasselfeldt tagesordnungspunkt b' : "Gerda Hasselfeldt",
 'petra pau überweisungsvorschlag' : "Petra Pau",
 'heuss formuliert'  : np.nan,
 'petra pau tagesordnungspunkt g' : "Petra Pau",
 'gerda hasselfeldt tagesordnungspunkt l' : "Gerda Hasselfeldt",
 'gerda hasselfeldt zusatzpunkt d' : "Gerda Hasselfeldt",
 'horst köhler sagte vor kurzem'  : np.nan,
 ' frauen' : np.nan,
 'petra pau berichterstattung' : "Petra Pau",
 'frieder meyer-krahmer'  : np.nan,
 'kabila wurde die devise ausgegeben'  : np.nan,
 'gerda hasselfeldt berichterstattung' : "Gerda Hasselfeldt",
 'angela merkel danken' : "	Angela Merkel",
 'petra pau tagesordnungspunkt i' : "Petra Pau",
 'katrin göring-eckardt tagesordnungspunkt l' : "Katrin Göring-Eckardt",
 'bundesregierung vor einigen monaten gesetzt'  : np.nan,
 'katrin göring-eckardt tagesordnungspunkt' : "Katrin Göring-Eckardt",
 'petra pau zusatzpunkt' : "Petra Pau",
 'merkel vor kurzem erklärt'  : np.nan,
 'katrin göring-eckardt tagesordnungspunkt d' : "Katrin Göring-Eckardt",
 'herr staatsminister bitte hermann gröhe' : "Hermann Gröhe",
 'köhler hat zur finanzkrise gesagt'  : np.nan,
 'gerda hasselfeldt tagesordnungspunkt u' : "Gerda Hasselfeldt",
 'gerda hasselfeldt grünbuch ten-v' : "Gerda Hasselfeldt",
 'gerda hasselfeldt tagesordnungspunkt mm' : "Gerda Hasselfeldt",
 'gerda hasselfeldt zusatzpunkt m' : "Gerda Hasselfeldt",
 'gerda hasselfeldt zusatzpunkt w' : "Gerda Hasselfeldt",
 'lammert sagte vor wenigen monaten'  : np.nan,
 'philipp rösler' : np.nan,
 'jan aken' : "Jan van Aken",
 'eckart klaeden' : "Eckart von Klaeden",
 'konstantin notz' : "Konstantin von Notz",
 'memet kilic' : "Memet Kılıç",
 'matthias w birkwald' : "Matthias Birkwald",
 'hermann e ott' : "Henning Otte",
 'obama hat drei elemente benannt': np.nan,
 'gerda hasselfeldt kollegen oppermann bekannt' : np.nan,
 'gabriele molitor' : "Gabi Molitor",
 'gerda hasselfeldt zusatzpunkt' : "Gerda Hasselfeldt",
 'petra pau tagesordnungspunkt e' : "Petra Pau",
 'lisa paus' : "Elisabeth Paus",
 'bitte staatsministerin cornelia pieper' : "Cornelia Pieper",
 'viola cramon-taubadel' : "Viola von Cramon-Taubadel",
 'johann david wadephul' : "Johann Wadephul",
 'patrick sensburg' : "Patrick Ernst Sensburg",
 'jean-claude trichet formulierte es so' : np.nan,
 'hans-georg der marwitz' : "Hans-Georg von der Marwitz",
 'aydan özo uz' : "Aydan Özoğuz",
 'angela merkel passiert ist': np.nan,
 'was haben ministerpräsidenten' : np.nan,
 'sonja amalie steffen' : "Sonja Steffen",
 'bitte cornelia pieper' : "Cornelia Pieper",
 'merkel gesagt'  : np.nan,
 'herr kampeter' : "Steffen Kampeter",
 'jens böhrnsen'  : np.nan,
 'christian wulff'  : np.nan,
 'pieper bitte cornelia pieper' : "Cornelia Pieper",
 'merkel die bildungsrepublik ausgerufen frage'  : np.nan,
 'schröder festgestellt'  : np.nan,
 'sarkozy drei vorstellungen'  : np.nan,
 'abgeordneten fraktionen ist'  : np.nan,
 'august hanning'  : np.nan,
 'jürgen zöllner' : np.nan,
 'herr staatssekretär werner hoyer' : "Werner Hoyer",
 'kohl der gesagt hat'  : np.nan,
 'eduard oswald berichterstattung' : "Eduard Oswald",
 'eduard oswald überweisungsvorschlag' : "Eduard Oswald",
 'eduard oswald tagesordnungspunkt' : "Eduard Oswald",
 'abschließen möchte ich mit einem zitat des rheinland-pfälzischen infrastrukturministers roger lewenz' : np.nan,
 'dazu hat der kollege stadler'  : np.nan,
 'südafrikas hat einmal gesagt' : np.nan,
 'eduard oswald halber frage ich'  : np.nan,
 'zeit gelassen'  : np.nan,
 'obama gesagt hat war'  : np.nan,
 'pieper bereit cornelia pieper'  : np.nan,
 'eduard oswald tagesordnungspunkt g'  : np.nan,
 'merkel sagen'  : np.nan,
 'michael link'  : np.nan,
 'angela merkel daraus folgt'  : np.nan,
 'jörg polheim' : "Jörg von Polheim",
 'joachim gauck' : np.nan,
 'hans-jürgen beerfeltz'  : np.nan,
 'bundesministerium der finanzen'  : np.nan,
 'bundesministerium für arbeit soziales'  : np.nan,
 'horst köhler sagte'  : np.nan,
 'merkel haben gesagt'  : np.nan,
 'merkel hier auf'  : np.nan,
 'merkel hier hingestellt gesagt'  : np.nan,
 'detlef scheele'  : np.nan,
 'johanna wanka' : np.nan,
 'schröder einmal skizziert'  : np.nan,
 'cornelia prüfer-storcks'  : np.nan,
 'ronald reagan'  : np.nan,
 'gauck der gesagt hat'  : np.nan,
 'dieter hundt hat ausgeführt'  : np.nan,
 'grillo hat des weiteren gesagt'  : np.nan,
 'eduard oswald tagesordnungspunkt s' : "Eduard Oswald",
 'katrin göring-eckardt tagesordnungspunkt cc' : "Katrin Göring-Eckardt",
 'katrin göring-eckardt tagesordnungspunkt yy' : "Katrin Göring-Eckardt",
 'pia zimmermann' : "Pia-Beate Zimmermann",
 'alexander s neu' : "Alexander Neu",
 'johanna wanka'  : np.nan,
 'manuela schwesig'  : np.nan,
 'ja thomas maizi re'  : np.nan,
 'andr hahn'  : np.nan,
 'johannes singhammer überweisungsvorschlag' : "Johannes Singhammer",
 'angela merkel damals sagte'  : np.nan,
 'charles m huber' : "Charles M. Huber",
 'ulle schauws' : "Ursula Schauws",
 'peter hintze tagesordnungspunkt b' : "Peter Hintze",
 'peter hintze tagesordnungspunkt' : "Peter Hintze",
 'michaela engelmeier' : "Michaela Engelmeier-Heite",
 'staatsministerin maria böhmer' : "Maria Böhmer",
 'philipp graf lerchenfeld' : "Philipp Graf von und zu Lerchenfeld",
 'elisabeth motschmann' : "Elisabeth Charlotte Motschmann",
 'volker ullrich' : "Volker Michael Ullrich",
 ' janukowitsch'  : np.nan,
 'gauck geschrieben hat sie schrieb'  : np.nan,
 'petra pau tagesordnungspunkt b' : "Petra Pau",
 'edelgard bulmahn überweisungsvorschlag' : "Edelgard Bulmahn",
 'sylvia jörrissen' : "Sylvia Jörrißen",
 'kees vries' : "Kees de Vries",
 'matern marschall' : "Matern von Marschall",
 'alois rainer' : "Alois Georg Josef Rainer",
 'joachim gauck diese zeilen'  : np.nan,
 'gauck zitieren'  : np.nan,
 'ulla schmidt überweisungsvorschlag' : "Ulla Schmidt",
 'bitte herr staatsminister michael roth' : "Michael Roth",
 'andr berghegger' : "André Berghegger",
 'christina jantz-herrmann' : "Christina Jantz",
 'edelgard bulmahn tagesordnungspunkt' : "Edelgard Bulmahn",
 'joachim gauck als er sagte'  : np.nan,
 ' putin'  : np.nan,
 'jochim pfeiffer' : "Joachim Pfeiffer",
 ' drobinski-weiß' : "Elvira Drobinski-Weiß",
 'abstimmung über den einzelplan'  : np.nan,
 'peter hintze tagesordnungspunkt f' : "Peter Hintze",
 'peter hintze tagesordnungspunkt l' : "Peter Hintze",
 'barsani hat mir gesagt'  : np.nan,
 'herr staatssekretär bitte klaus-dieter fritsche' : "",
 'klaus-dieter fritsche'  : np.nan,
 'herr staatsminister bitte michael roth' : "Michael Roth",
 'herr staatsminister michael roth' : "Michael Roth",
 'gauck hat es treffend formuliert'  : np.nan,
 'jutta blankau-rosenfeldt'  : np.nan,
 'claudia roth überweisungsvorschlag' : "Claudia Roth",
 'edelgard bulmahn tagesordnungspunkt iv e' : "Edelgard Bulmahn",
 'edelgard bulmahn drucksache überweisungsvorschlag' : "Edelgard Bulmahn",
 'obama unter freunden'  : np.nan,
 'putin aussehen muss man sagen'  : np.nan,
 'claudia roth schließungsantrag ist abgelehnt' : "Claudia Roth",
 'ulla schmidt tagesordnungspunkt' : "Ulla Schmidt",
 'danke michael roth' : "Michael Roth",
 'peter hintze überweisungsvorschlag' : "Peter Hintze",
 'claudia roth tagesordnungspunkt b' : "Claudia Roth",
 'agenda zurückdrängen'  : np.nan,
 'claudia roth zusatzpunkt d' : "Claudia Roth",
 'ulla schmidt drucksache überweisungsvorschlag' : "Ulla Schmidt",
 'obama doch einmal eins erklären' : np.nan,
 'ulla schmidt zusatzpunkt' : "Ulla Schmidt",
 'johannes singhammer tagesordnungspunkt i' : "Johannes Singhammer",
 ' entscheidungen'  : np.nan,
 'putin war'  : np.nan,
 'willy brandt abschließen'  : np.nan,
 ' herausforderung' : np.nan,
 'erdogan seiner politik gilt' : np.nan,
 'frankreichs hat gesagt'  : np.nan,
 'herr dobrindt'  : np.nan,
 'putin gegenüber deutlich gemacht -'  : np.nan,
 'ankündigungsprogramm bleibt'  : np.nan,
 'malu dreyer' : np.nan,
 'lammert ich erinnere mich noch'  : np.nan,
 'helmut schmidt formulierte das so'  : np.nan,
 'claudia roth https' : "Claudia Roth",
 'merkel die heute sagte'  : np.nan,
 'joachim gauck gesagt hat'  : np.nan,
 'petra pau zusatzpunkt f'  : np.nan,
 'eva-maria schreiber' : "Eva Schreiber",
 'elvan korkmaz-emre' : "Elvan Korkmaz",
 'bettina margarethe wiesmann' : "Bettina Wiesmann",
 'franziska giffey'  : np.nan,
 'svenja schulze'  : np.nan,
 'helin evrim sommer'  : np.nan,
 'thomas opperman'  : np.nan,
 'norbert maria altenkamp' : "Norbert Altenkamp",
 'britta katharina dassler' : "Britta Dassler",
 'andreas geisel'  : np.nan,
 'nezahat baradari'  : np.nan,
 'gerhard zickenheiner'  : np.nan,
 'peter heidt'  : np.nan,
 'isabel mackensen'  : np.nan,
 'elke breitenbach'  : np.nan,
 'sandra bubendorfer-licht'  : np.nan,
 'joe weingarten'  : np.nan,
 'sylvia lehmann'  : np.nan,
 'bela bach'  : np.nan,
 'matthias nölke'  : np.nan,
 'charlotte schneidewind-hartnagel'  : np.nan,
 'dorothee martin'  : np.nan,
 'saskia ludwig'  : np.nan,
 'janosch dahmen'  : np.nan,
 'christian natterer'  : np.nan,
 'christopher gohl'  : np.nan,
 'maika friemann-jennert'  : np.nan}

In [31]:
def apply_mapping(mapping_dic, value): 
    if value in mapping_dic.keys(): 
        res = mapping_dic[value]    
    else: 
        res = np.nan
    return res

## Mapping

In [872]:
#PolID2SpeechID_df["mapped_name"] = PolID2SpeechID_df["name"].map(lambda x: find_most_similiar_name_levenshtein(x))

In [33]:
PolID2SpeechID_df_copy = PolID2SpeechID_df.copy()

In [34]:
#PolID2SpeechID_df = PolID2SpeechID_df_copy.copy()

In [35]:
PolID2SpeechID_df["mapped_name"] = PolID2SpeechID_df["name"].map(lambda x: apply_mapping(name_mapping_dic, x))

In [36]:
PolID2SpeechID_df.head(30)

,politicianID,speeches,firstName,lastName,surname_lower,forename_lower,name,mapped_name
0,11000246,"['471526', '479132', '489844']",Willy,Brandt,brandt,willy,willy brandt,NaN
1,11002287,"['471554', '471574', '471612', '471651', '4716...",Rita,Süssmuth,süssmuth,rita,rita süssmuth,NaN
2,11002354,"['471532', '471825', '471980', '472676', '4738...",Wolfgang,Ullmann,ullmann,wolfgang,wolfgang ullmann,NaN
3,11000418,"['471527', '471596', '471692', '473651', '4794...",alfred,dregger,dregger,alfred,alfred dregger,NaN
4,11000891,"['471536', '471967', '472560', '473468', '4739...",uwe-jens,heuer,heuer,uwe-jens,uwe-jens heuer,NaN
5,11000230,"['471538', '471673', '472056', '472587', '4735...",Friedrich,Bohl,bohl,friedrich,friedrich bohl,NaN
6,11002278,"['471540', '471675', '472604', '473359', '4734...",Peter,Struck,struck,peter,peter struck,NaN
7,11002557,"['471542', '478009', '484489', '487349', '4916...",Torsten,Wolfgramm,wolfgramm,torsten,torsten wolfgramm,NaN
8,11001159,"['471544', '471969', '472461', '472749', '4731...",Ingrid,Köppe,köppe,ingrid,ingrid köppe,NaN
9,11000127,"['471547', '471584', '471949', '472553', '4734...",Helmuth,Becker,becker,helmuth,helmuth becker,NaN
10,11000342,"['471549', '471874', '472148', '472767', '4728...",Dieter-Julius,Cronenberg,cronenberg,dieter-julius,dieter-julius cronenberg,NaN
11,11001114,"['471551', '471729', '472071', '472471', '4726...",Hans,Klein,klein,hans,hans klein,NaN
12,11002016,"['471553', '472878', '473510', '473854', '4740...",Renate,Schmidt,schmidt,renate,renate schmidt,NaN
13,11002379,"['471561', '471594', '471684', '472771', '4736...",Hans-Jochen,Vogel,vogel,hans-jochen,hans-jochen vogel,NaN
14,11001272,"['471568', '471599', '471795', '472070', '4725...",otto graf,lambsdorff,lambsdorff,otto graf,otto graf lambsdorff,NaN
15,11001165,"['471556', '471592', '471657', '471738', '4736...",Helmut,Kohl,kohl,helmut,helmut kohl,NaN
16,11000228,"['471559', '479212', '494734', '494824', '4971...",Wolfgang,Bötsch,bötsch,wolfgang,wolfgang bötsch,NaN
17,11000425,"['471567', '472797', '474774', '474960', '4765...",freimut,duve,duve,freimut,freimut duve,NaN
18,11000629,"['471569', '471611', '480892', '482285', '4943...",jörg,ganschow,ganschow,jörg,jörg ganschow,Jörg Wolfgang Ganschow
19,113,"['471571', '471603', '472660', '472775']",nan,Gysi,gysi,nan,nan gysi,NaN
20,11002721,"['471573', '471609', '472666', '474154', '4753...",Vera,Lengsfeld,lengsfeld,vera,vera lengsfeld,Vera Lengsfeld
21,11002259,"['471575', '471628', '477098', '478953', '4802...",Gerhard,Stoltenberg,stoltenberg,gerhard,gerhard stoltenberg,NaN
22,11002153,"['471577', '471841', '472478', '473425', '4740...",Ilja,Seifert,seifert,ilja,ilja seifert,NaN
23,11002108,"['471579', '471708', '472529', '473370', '4735...",werner,schulz,schulz,werner,werner schulz,NaN
24,11002503,"['471583', '476948', '478258', '481094', '4825...",Heidemarie,Wieczorek-Zeul,wieczorek-zeul,heidemarie,heidemarie wieczorek-zeul,NaN
25,11001293,"['471597', '471963', '473858', '476329', '4791...",Paul,Laufs,laufs,paul,paul laufs,NaN
26,11001938,"['471616', '471951', '473802', '474338', '4749...",Wolfgang,Schäuble,schäuble,wolfgang,wolfgang schäuble,NaN
27,11002696,"['471618', '471955', '472554', '472840', '4734...",klaus,kinkel,kinkel,klaus,klaus kinkel,NaN
28,11000661,"['471614', '471731', '472769', '473700', '4741...",Hans-Dietrich,Genscher,genscher,hans-dietrich,hans-dietrich genscher,NaN
29,11002412,"['471620', '471713', '472513', '473486', '4740...",Theodor,Waigel,waigel,theodor,theodor waigel,NaN

In [37]:
def get_forename(str_): 
    if type(str_) == str: 
        res = ' '.join(str_.split(" ")[:-1]).lower()
    elif type(str_) == float: 
        res = np.nan
        
    return res
        

def get_surname(str_): 
    if type(str_) == str: 
        res = str_.split(" ")[-1].lower()
    elif type(str_) == float: 
        res = np.nan
        
    return res

PolID2SpeechID_df["forename_lower_mapped"] = PolID2SpeechID_df["mapped_name"].map(lambda x: get_forename(x))
PolID2SpeechID_df["surname_lower_mapped"] = PolID2SpeechID_df["mapped_name"].map(lambda x: get_surname(x))

In [38]:
PolID2SpeechID_df["surname_lower_comb"] = np.where(PolID2SpeechID_df['surname_lower_mapped'].isna() != True, 
                                                    PolID2SpeechID_df['surname_lower_mapped'], 
                                                    PolID2SpeechID_df['surname_lower'])

PolID2SpeechID_df["forename_lower_comb"] = np.where(PolID2SpeechID_df['forename_lower_mapped'].isna() != True, 
                                                    PolID2SpeechID_df['forename_lower_mapped'], 
                                                    PolID2SpeechID_df['forename_lower'])

In [39]:
PolID2SpeechID_df.head(2)

,politicianID,speeches,firstName,lastName,surname_lower,forename_lower,name,mapped_name,forename_lower_mapped,surname_lower_mapped,surname_lower_comb,forename_lower_comb
0,11000246,"['471526', '479132', '489844']",Willy,Brandt,brandt,willy,willy brandt,NaN,NaN,NaN,brandt,willy
1,11002287,"['471554', '471574', '471612', '471651', '4716...",Rita,Süssmuth,süssmuth,rita,rita süssmuth,NaN,NaN,NaN,süssmuth,rita

In [751]:
#test3 = pd.merge(ID_and_names_from_Wiki, PolID2SpeechID_df, how = "left", on=["forename_lower", "surname_lower"])

In [44]:
PolID2SpeechID_df[PolID2SpeechID_df['surname_lower_mapped'].isna() != True].head(5)

,politicianID,speeches,firstName,lastName,surname_lower,forename_lower,name,mapped_name,forename_lower_mapped,surname_lower_mapped,surname_lower_comb,forename_lower_comb
18,11000629,"['471569', '471611', '480892', '482285', '4943...",jörg,ganschow,ganschow,jörg,jörg ganschow,Jörg Wolfgang Ganschow,jörg wolfgang,ganschow,ganschow,jörg wolfgang
20,11002721,"['471573', '471609', '472666', '474154', '4753...",Vera,Lengsfeld,lengsfeld,vera,vera lengsfeld,Vera Lengsfeld,vera,lengsfeld,lengsfeld,vera
30,11001520,"['471622', '471767', '472068', '472670', '4741...",Jürgen W,Möllemann,möllemann,jürgen w,jürgen w möllemann,Jürgen Möllemann,jürgen,möllemann,möllemann,jürgen
39,11002120,"['471642', '471931', '472484', '474035', '4741...",Irmgard,Schwaetzer,schwaetzer,irmgard,irmgard schwaetzer,Irmgard Adam-Schwaetzer,irmgard,adam-schwaetzer,adam-schwaetzer,irmgard
61,11001301,"['471781', '472409', '474847', '474950', '4770...",andrea,gysi,gysi,andrea,andrea gysi,Andrea Gysi,andrea,gysi,gysi,andrea

In [46]:
test3 = pd.merge(ID_and_names_from_Wiki, PolID2SpeechID_df, how = "left", left_on=["forename_lower", "surname_lower"], right_on=["forename_lower_comb", "surname_lower_comb"])

In [47]:
test3.columns

Index(['pageid', 'wikidataid', 'name_x', 'surname_lower_x', 'forename_lower_x',
       'politicianID', 'speeches', 'firstName', 'lastName', 'surname_lower_y',
       'forename_lower_y', 'name_y', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb'],
      dtype='object')

In [48]:
test3 = test3[['pageid', 'wikidataid', 'name_x', 'surname_lower_x', 'forename_lower_x',
       'politicianID', 'speeches', 'firstName', 'lastName', 'mapped_name', 'surname_lower_comb', 'forename_lower_comb']]

In [49]:
test3["speeches"].isna().value_counts()

False    2450
True      171
Name: speeches, dtype: int64

In [50]:
len(test3["wikidataid"][test3["speeches"].isna() == False].unique()) # 1988

2040

In [51]:
test4 = pd.merge(PolID2SpeechID_df, ID_and_names_from_Wiki, how = "left", right_on=["forename_lower", "surname_lower"], left_on=["forename_lower_comb", "surname_lower_comb"])

In [52]:
test4.head(2)

,politicianID,speeches,firstName,lastName,surname_lower_x,forename_lower_x,name_x,mapped_name,forename_lower_mapped,surname_lower_mapped,surname_lower_comb,forename_lower_comb,pageid,wikidataid,name_y,surname_lower_y,forename_lower_y
0,11000246,"['471526', '479132', '489844']",Willy,Brandt,brandt,willy,willy brandt,NaN,NaN,NaN,brandt,willy,1518001.0,Q2514,Willy Brandt,brandt,willy
1,11002287,"['471554', '471574', '471612', '471651', '4716...",Rita,Süssmuth,süssmuth,rita,rita süssmuth,NaN,NaN,NaN,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita

In [53]:
test4["speeches"].isna().value_counts()

False    2802
Name: speeches, dtype: int64

In [55]:
len(test4), len(test3) # test3 based on ID_and_names_from_Wiki, test4 based on PolID2SpeechID_df

(2802, 2621)

In [56]:
test4.columns

Index(['politicianID', 'speeches', 'firstName', 'lastName', 'surname_lower_x',
       'forename_lower_x', 'name_x', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb',
       'pageid', 'wikidataid', 'name_y', 'surname_lower_y',
       'forename_lower_y'],
      dtype='object')

In [57]:
test4 = test4[['politicianID', 'speeches', 'surname_lower_comb', "mapped_name", 'forename_lower_comb',
       'pageid', 'wikidataid', 'name_y', 'surname_lower_y',
       'forename_lower_y']]

In [58]:
len(test4) - len(test4[test4["wikidataid"].isna() == True])

2450

In [59]:
unique_wiki_ids = list(test4["wikidataid"].unique())
len(unique_wiki_ids)#, unique_wiki_ids

2041

In [60]:
len(ID_and_names_from_Wiki)

2358

In [61]:
test4[test4["mapped_name"].isna() == False].head(20)

,politicianID,speeches,surname_lower_comb,mapped_name,forename_lower_comb,pageid,wikidataid,name_y,surname_lower_y,forename_lower_y
18,11000629,"['471569', '471611', '480892', '482285', '4943...",ganschow,Jörg Wolfgang Ganschow,jörg wolfgang,6110269.0,Q1715571,Jörg Wolfgang Ganschow,ganschow,jörg wolfgang
20,11002721,"['471573', '471609', '472666', '474154', '4753...",lengsfeld,Vera Lengsfeld,vera,NaN,NaN,NaN,NaN,NaN
30,11001520,"['471622', '471767', '472068', '472670', '4741...",möllemann,Jürgen Möllemann,jürgen,10892.0,Q65521,Jürgen Möllemann,möllemann,jürgen
39,11002120,"['471642', '471931', '472484', '474035', '4741...",adam-schwaetzer,Irmgard Adam-Schwaetzer,irmgard,15615.0,Q74226,Irmgard Adam-Schwaetzer,adam-schwaetzer,irmgard
64,11001301,"['471781', '472409', '474847', '474950', '4770...",gysi,Andrea Gysi,andrea,NaN,NaN,NaN,NaN,NaN
68,11001931,"['471849', '473856', '475951', '476542', '4771...",schäfer,Harald B. Schäfer,harald b.,1289639.0,Q1584397,Harald B. Schäfer,schäfer,harald b.
70,11000111,"['471851', '474348', '475959', '477691', '4785...",baum,Gerhart Baum,gerhart,71107.0,Q518517,Gerhart Baum,baum,gerhart
77,11001820,"['471891', '472098', '473749', '476617', '4768...",renesse,Margot von Renesse,margot von,1274531.0,Q1453707,Margot von Renesse,renesse,margot von
92,11002058,"['471982', '475443', '479334', '479441', '4811...",schönburg-glauchau,Joachim Graf von Schönburg-Glauchau,joachim graf von,2081863.0,Q105335,Joachim Graf von Schönburg-Glauchau,schönburg-glauchau,joachim graf von
162,11001827,"['472526', '495656', '504198', '504932', '5053...",reuschenbach,Peter Reuschenbach,peter,2000450.0,Q2077829,Peter Reuschenbach,reuschenbach,peter
165,107,['472548'],maiziere,Thomas de Maiziere,thomas de,NaN,NaN,NaN,NaN,NaN
168,11002247,"['472570', '474132', '475418', '475630', '4786...",stetten,Wolfgang von Stetten,wolfgang von,1101111.0,Q98757,Wolfgang von Stetten,stetten,wolfgang von
178,112,['472626'],logischen,Cornelia von Teichman und Logischen,cornelia von teichman und,6585379.0,Q1133468,Cornelia von Teichman und Logischen,logischen,cornelia von teichman und
183,11002066,"['472642', '473162', '475391', '477786', '4785...",schorlemer,Reinhard von Schorlemer,reinhard von,616684.0,Q1309053,Reinhard von Schorlemer,schorlemer,reinhard von
186,11001171,"['472662', '474803', '475367', '479015', '4798...",kolb,Heinrich Leonhard Kolb,heinrich leonhard,174092.0,Q1598169,Heinrich Leonhard Kolb,kolb,heinrich leonhard
210,117,['472843'],kohl,Helmut Kohl,helmut,2155.0,Q2518,Helmut Kohl,kohl,helmut
240,11000207,"['473124', '477224', '481670', '489993', '4910...",blunck,Lieselott Blunck,lieselott,3993811.0,Q1824295,Lieselott Blunck,blunck,lieselott
250,11001008,"['473394', '476749', '479712', '493222', '4936...",jaffke,Susanne Jaffke,susanne,174262.0,Q2369278,Susanne Jaffke,jaffke,susanne
255,11001887,"['473396', '477148', '478457', '481816', '4851...",rossmanith,Kurt Rossmanith,kurt,175561.0,Q1794023,Kurt Rossmanith,rossmanith,kurt
269,11002536,"['473472', '473843', '474125', '476820', '4795...",with,Hans de With,hans de,958084.0,Q1257864,Hans de With,with,hans de

In [63]:
ID_and_names_from_Wiki[ID_and_names_from_Wiki["surname_lower"] == "lengsfeld"]

       pageid wikidataid               name surname_lower forename_lower
1792  7793813  Q15439343  Philipp Lengsfeld     lengsfeld        philipp

In [64]:
ID_and_names_from_Wiki[ID_and_names_from_Wiki["forename_lower"] == "vera"]

      pageid wikidataid               name surname_lower forename_lower
2212  292497   Q1486123       Vera Dominke       dominke           vera
2213  175490    Q107737  Vera Wollenberger  wollenberger           vera

In [62]:
ID_and_names_from_Wiki.head()

     pageid wikidataid           name surname_lower forename_lower
0   1713670     Q77685    Özcan Mutlu         mutlu          özcan
1  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
2  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
3  10062062  Q40998599  Zaklin Nastic        nastic         zaklin
4  10062062  Q40998599  Zaklin Nastic        nastic         zaklin

In [72]:
test3.columns

Index(['pageid', 'wikidataid', 'name_x', 'surname_lower_x', 'forename_lower_x',
       'politicianID', 'speeches', 'firstName', 'lastName', 'mapped_name',
       'surname_lower_comb', 'forename_lower_comb'],
      dtype='object')

In [73]:
test4.columns

Index(['politicianID', 'speeches', 'surname_lower_comb', 'mapped_name',
       'forename_lower_comb', 'pageid', 'wikidataid', 'name_y',
       'surname_lower_y', 'forename_lower_y'],
      dtype='object')

In [83]:
test3_for_comparison = test3[['pageid', 'wikidataid', 'name_x', 'surname_lower_x', 'forename_lower_x',
       'politicianID', 'speeches','mapped_name',
       'surname_lower_comb', 'forename_lower_comb']].copy()

In [84]:
test4_for_comparison =test4[['politicianID', 'speeches', 'surname_lower_comb', 'mapped_name',
       'forename_lower_comb', 'pageid', 'wikidataid', 'name_y',
       'surname_lower_y', 'forename_lower_y']].copy()

In [89]:
test3_for_comparison = test3_for_comparison.rename(columns = {"surname_lower_x": "surname_lower", 
                                                              "forename_lower_x": "forename_lower", 
                                                             "name_x" : "name"})

In [90]:
test4_for_comparison = test4_for_comparison.rename(columns = {"surname_lower_y": "surname_lower", 
                                                              "forename_lower_y": "forename_lower", 
                                                             "name_y": "name"})

In [91]:
df_diff = pd.concat([test3_for_comparison[['pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower',
       'politicianID', 'speeches', 'mapped_name',
       'surname_lower_comb', 'forename_lower_comb']],
                     test4_for_comparison[['politicianID', 'speeches', 'surname_lower_comb', 'mapped_name',
       'forename_lower_comb', 'pageid', 'wikidataid', 'name',
       'surname_lower', 'forename_lower']]]).drop_duplicates(keep=False)

In [92]:
df_diff

,pageid,wikidataid,name,surname_lower,forename_lower,politicianID,speeches,mapped_name,surname_lower_comb,forename_lower_comb
27,8898664.0,Q20645389,Albrecht Glaser,glaser,albrecht,NaN,NaN,NaN,NaN,NaN
33,1647329.0,Q1670311,Alexander Gauland,gauland,alexander,NaN,NaN,NaN,NaN,NaN
52,9716234.0,Q27975838,Alice Weidel,weidel,alice,NaN,NaN,NaN,NaN,NaN
54,413173.0,Q1304832,Alois Graf von Waldburg-Zeil,waldburg-zeil,alois graf von,NaN,NaN,NaN,NaN,NaN
60,3623727.0,Q1764708,André Hahn,hahn,andré,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2796,NaN,NaN,NaN,NaN,NaN,2459.0,"['1049864', '1054582', '1064710']",NaN,ludwig,saskia
2797,NaN,NaN,NaN,NaN,NaN,11004962.0,"['1052982', '1054475', '1056125', '1056727', '...",NaN,dahmen,janosch
2799,NaN,NaN,NaN,NaN,NaN,2442.0,['1057729'],NaN,natterer,christian
2800,NaN,NaN,NaN,NaN,NaN,2463.0,"['1062535', '1065335']",NaN,gohl,christopher
2801,NaN,NaN,NaN,NaN,NaN,2455.0,['1063204'],NaN,friemann-jennert,maika

In [ ]:
# test3 based on ID_and_names_from_Wiki, test4 based on PolID2SpeechID_df

In [93]:
len(ID_and_names_from_Wiki) - len(df_diff)

1867

In [97]:
len(test3) - len(test3[test3["wikidataid"].isna() == True])

2621

In [98]:
len(test4) - len(test4[test4["speeches"].isna() == True])

2802

In [102]:
PolID2SpeechID_df.columns

Index(['politicianID', 'speeches', 'firstName', 'lastName', 'surname_lower',
       'forename_lower', 'name', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb'],
      dtype='object')

In [103]:
ID_and_names_from_Wiki.columns

Index(['pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower'], dtype='object')

In [311]:
test5 = pd.merge(PolID2SpeechID_df[['politicianID', 'speeches', 'mapped_name', 'forename_lower_mapped', 'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb']], 
                 ID_and_names_from_Wiki, 
                 how = "outer", 
                 right_on=["forename_lower", "surname_lower"], 
                 left_on=["forename_lower_comb", "surname_lower_comb"])

In [312]:
len(test3), len(test4), len(test5) #(2621, 2802, 2973)

(2429, 2634, 2973)

In [313]:
test5.columns

Index(['politicianID', 'speeches', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb',
       'pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower'],
      dtype='object')

In [314]:
test5_for_comparison = test5.rename(columns = {"surname_lower_y": "surname_lower", 
                                               "forename_lower_y": "forename_lower", 
                                               "name_y": "name"})

In [315]:
test5_for_comparison.columns

Index(['politicianID', 'speeches', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb',
       'pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower'],
      dtype='object')

In [316]:
df_diff45 = pd.concat([test4_for_comparison[['pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower',
       'politicianID', 'speeches', 'mapped_name',
       'surname_lower_comb', 'forename_lower_comb']],
                     test5_for_comparison[['politicianID', 'speeches', 'surname_lower_comb', 'mapped_name',
       'forename_lower_comb', 'pageid', 'wikidataid', 'name',
       'surname_lower', 'forename_lower']]]).drop_duplicates(keep=False)

In [317]:
len(df_diff45)

139

In [318]:
df_diff35 = pd.concat([test3_for_comparison[['pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower',
       'politicianID', 'speeches', 'mapped_name',
       'surname_lower_comb', 'forename_lower_comb']],
                     test5_for_comparison[['politicianID', 'speeches', 'surname_lower_comb', 'mapped_name',
       'forename_lower_comb', 'pageid', 'wikidataid', 'name',
       'surname_lower', 'forename_lower']]]).drop_duplicates(keep=False)

In [319]:
len(df_diff35)

352

In [320]:
test5

,politicianID,speeches,mapped_name,forename_lower_mapped,surname_lower_mapped,surname_lower_comb,forename_lower_comb,pageid,wikidataid,name,surname_lower,forename_lower
0,11000246.0,"['471526', '479132', '489844']",NaN,NaN,NaN,brandt,willy,1518001.0,Q2514,Willy Brandt,brandt,willy
1,11002287.0,"['471554', '471574', '471612', '471651', '4716...",NaN,NaN,NaN,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
2,820.0,"['476168', '480165', '489840', '491651', '4919...",Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
3,154.0,['479382'],Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
4,903.0,"['487806', '489841', '491652', '514122', '5164...",Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
...,...,...,...,...,...,...,...,...,...,...,...,...
2968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10060211.0,Q40998789,Waldemar Herdt,herdt,waldemar
2969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5648319.0,Q2543629,Walter Bersch,bersch,walter
2970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,544564.0,Q103160,Wilhelm von Gottberg,gottberg,wilhelm von
2971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6069511.0,Q2591496,Wolfgang Steiger,steiger,wolfgang
2972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10065443.0,Q40980201,Wolfgang Wiehle,wiehle,wolfgang

In [321]:
len(test5[test5["speeches"].isna() == False]), len(test5[test5["wikidataid"].isna() == False])

(2802, 2621)

In [322]:
test3 = test3.drop_duplicates()

In [323]:
len(test3)

2429

In [324]:
test4 = test4.drop_duplicates()

In [325]:
len(test4)

2634

In [326]:
test5 = test5.drop_duplicates()

In [327]:
len(test5)

2781

In [328]:
test5[test5.duplicated("wikidataid") == True]

,politicianID,speeches,mapped_name,forename_lower_mapped,surname_lower_mapped,surname_lower_comb,forename_lower_comb,pageid,wikidataid,name,surname_lower,forename_lower
2,820.0,"['476168', '480165', '489840', '491651', '4919...",Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
3,154.0,['479382'],Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
4,903.0,"['487806', '489841', '491652', '514122', '5164...",Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
13,444.0,"['484018', '487174', '509683', '517755']",Helmuth Becker,helmuth,becker,becker,helmuth,394854.0,Q1604393,Helmuth Becker,becker,helmuth
14,390.0,['509682'],Helmuth Becker,helmuth,becker,becker,helmuth,394854.0,Q1604393,Helmuth Becker,becker,helmuth
...,...,...,...,...,...,...,...,...,...,...,...,...
2796,2459.0,"['1049864', '1054582', '1064710']",NaN,NaN,NaN,ludwig,saskia,NaN,NaN,NaN,NaN,NaN
2797,11004962.0,"['1052982', '1054475', '1056125', '1056727', '...",NaN,NaN,NaN,dahmen,janosch,NaN,NaN,NaN,NaN,NaN
2799,2442.0,['1057729'],NaN,NaN,NaN,natterer,christian,NaN,NaN,NaN,NaN,NaN
2800,2463.0,"['1062535', '1065335']",NaN,NaN,NaN,gohl,christopher,NaN,NaN,NaN,NaN,NaN
2801,2455.0,['1063204'],NaN,NaN,NaN,friemann-jennert,maika,NaN,NaN,NaN,NaN,NaN

In [329]:
test5[test5["wikidataid"] == "Q66286"]

,politicianID,speeches,mapped_name,forename_lower_mapped,surname_lower_mapped,surname_lower_comb,forename_lower_comb,pageid,wikidataid,name,surname_lower,forename_lower
1,11002287.0,"['471554', '471574', '471612', '471651', '4716...",NaN,NaN,NaN,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
2,820.0,"['476168', '480165', '489840', '491651', '4919...",Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
3,154.0,['479382'],Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita
4,903.0,"['487806', '489841', '491652', '514122', '5164...",Rita Süssmuth,rita,süssmuth,süssmuth,rita,4253.0,Q66286,Rita Süssmuth,süssmuth,rita

In [330]:
test5[test5["wikidataid"] == "Q66286"]["speeches"]

1    ['471554', '471574', '471612', '471651', '4716...
2    ['476168', '480165', '489840', '491651', '4919...
3                                           ['479382']
4    ['487806', '489841', '491652', '514122', '5164...
Name: speeches, dtype: object

In [331]:
list(test5[test5["wikidataid"] == "Q66286"]["speeches"])[0].replace('[', '').replace(']', '').replace("'", '')#.replace("'", ' ')

'471554, 471574, 471612, 471651, 471680, 471689, 471975, 472533, 472790, 472897, 473127, 473497, 473498, 473646, 473896, 474123, 474703, 474936, 474955, 475214, 475617, 476166, 476192, 476867, 477136, 477447, 477569, 478276, 479001, 479380, 479381, 479449, 479472, 479617, 479827, 480178, 480699, 481000, 481379, 481914, 482319, 482710, 483137, 483497, 484632, 484692, 484805, 485050, 485447, 485639, 486327, 486615, 486905, 487531, 487609, 487861, 488511, 488874, 489114, 489657, 489857, 491324, 491649, 491676, 491939, 492024, 492519, 492812, 493084, 493567, 493708, 494270, 494466, 494725, 494780, 494908, 495066, 495340, 495668, 496065, 496425, 496657, 497005, 497135, 497799, 498015, 498056, 498724, 498781, 499393, 499574, 499835, 500208, 500274, 501380, 501663, 502312, 502673, 503035, 503190, 503328, 503815, 504289, 504659, 504915, 505423, 505442, 505755, 506071, 506439, 506895, 507177, 507434, 507531, 507665, 508335, 508627, 509039, 509082, 509395, 509525, 510054, 510553, 511153, 511293, 511330, 511411, 512027, 512334, 512966, 512986, 513164, 513396, 514548, 514647, 515000, 515634, 515636, 515872, 516278, 516434, 516524, 516729, 517169, 517215, 517907, 517944, 518547, 518500, 518606, 518800, 518869, 519760, 519844, 520182, 520314, 520929, 521453, 521535, 521752, 522077, 522178, 522411, 522944, 523303, 523558, 523372, 523736, 523957, 524412, 524679, 525261, 525719, 526086, 526423, 526579, 526828, 527375, 528261, 528346, 528518, 528537, 528848, 528956, 529560, 529594, 529599, 529636, 529686, 529811, 530066, 530163, 530392, 530613, 530824, 531054, 531469, 531627, 531807, 532313, 532554, 533158, 533290, 533484, 533982, 534203, 534941, 535223, 535591, 535749, 536146, 536202, 536526, 537171, 537909, 538684, 539151, 539292, 539555, 539911, 540342, 540530, 540712, 540737, 540953, 541194, 541538, 541668, 542172, 542277, 542394, 542590, 543106, 543748, 544430, 544581, 544664, 544847, 545021, 545313, 545735, 546594, 546682, 547028, 547444, 547512, 547704, 548077, 548316, 548339, 548617, 548963, 549280, 549397, 549716, 550101, 550315, 550956, 551149, 551882, 552446, 552479, 552881, 553002, 553230, 553571, 553802, 553893, 554562, 554683, 554938, 555417, 555556, 556135, 556281, 556434, 556828, 557276, 558229, 558261, 558388, 558415, 558500, 558649, 558846, 558813, 559216, 559269, 559908, 560807, 560881, 561036, 561398, 561901, 562575, 562685, 563082, 563436, 563547, 563953, 564067, 564338, 564825, 565400, 565407, 565625, 565779, 566439, 566702, 566815, 567133, 567502, 568089, 568282, 568556, 568783, 569184, 569483, 569695, 570017, 570316, 570727, 570999, 571048, 571375, 571446, 571509, 571637, 572045, 572244, 572507, 572724, 573409, 573554, 573576, 573619, 573745, 573977, 574287, 574741, 575385, 575758, 576109, 576543, 576572, 577120, 577429, 577620, 577865, 578160, 578503, 578911, 579268, 579291, 579642, 579874, 580204, 580235, 580588, 580687, 580863, 581187, 581561, 582399, 582418, 582664, 582949, 583011, 583260, 583854, 584006, 584335, 584614, 584818, 585180, 585297, 585786, 585829, 586082, 586235, 586613, 586701, 586883, 586996, 591747, 593403, 596824, 597299, 599619, 601974, 603623, 604217, 608458, 608906, 634648, 639709'

In [333]:
#[int(item) for item in list(test5[test5["wikidataid"] == "Q66286"]["speeches"])[0].replace('[', '').replace(']', '').replace("'", '').split(", ")]

In [335]:
#for wikiid in test5["wikidataid"].unique()

In [336]:
len(test5["wikidataid"].unique())

2188

In [337]:
list(test5[test5["wikidataid"] == "Q20645389"]["speeches"])[0] is np.nan

True

In [338]:
test5.columns

Index(['politicianID', 'speeches', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb',
       'pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower'],
      dtype='object')

In [343]:
max(list(test5[test5["wikidataid"] == "Q66286"]["politicianID"]))

11002287.0

In [344]:
unique_wikiIDs = [item for item in test5["wikidataid"].unique() if item is not np.nan]

speeches_for_df = []
unique_wikiIDs_for_df = []
politicianIDs_for_df = []

for wikiID in unique_wikiIDs: 
    length = len(test5[test5["wikidataid"] == wikiID]["speeches"])
    
    politicianIDs_for_df.append(max(list(test5[test5["wikidataid"] == wikiID]["politicianID"])))
    
    speeches_list = []
    
    
    try:     
        for i in range(length): 
            
            temp_list = list(test5[test5["wikidataid"] == wikiID]["speeches"])[i]
            
            if temp_list is not np.nan: 
            
                speeches_list.append([int(item) for item in temp_list.replace('[', '').replace(']', '').replace("'", '').split(", ")])                

        speeches_list_final = [item for sublist in speeches_list for item in sublist]

        speeches_for_df.append(speeches_list_final)
        unique_wikiIDs_for_df.append(wikiID)

    except (AttributeError, TypeError): 
        print(wikiID, speeches_list)

In [345]:
len(speeches_for_df), len(unique_wikiIDs_for_df), len(politicianIDs_for_df)

(2187, 2187, 2187)

In [358]:
politicianIDs_for_df[-10:]

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

NamesAndSpeeches = pd.DataFrame(list(zip(unique_wikiIDs_for_df, speeches_for_df, politicianIDs_for_df)), columns =['WikiIDs', 'speeches', "politicianID"])

In [356]:
NamesAndSpeeches

,WikiIDs,speeches,politicianID
0,Q2514,"[471526, 479132, 489844]",11000246.0
1,Q66286,"[471554, 471574, 471612, 471651, 471680, 47168...",11002287.0
2,Q895636,"[471532, 471825, 471980, 472676, 473851, 47411...",11002354.0
3,Q65389,"[471527, 471596, 471692, 473651, 479473, 50886...",11000418.0
4,Q1594398,"[471536, 471967, 472560, 473468, 473996, 47411...",11000891.0
...,...,...,...
2182,Q40998789,[],NaN
2183,Q2543629,[],NaN
2184,Q103160,[],NaN
2185,Q2591496,[],NaN
2186,Q40980201,[],NaN

In [359]:
len(test5[test5["speeches"].isna()])

147

In [360]:
def zero_lengths_to_na(speeches): 
    if len(speeches) == 0: 
        res = np.nan
    else:
        res = speeches
        
    return res

In [361]:
NamesAndSpeeches["speeches"] = NamesAndSpeeches["speeches"].map(lambda x: zero_lengths_to_na(x))

In [362]:
NamesAndSpeeches.head()

    WikiIDs                                           speeches  politicianID
0     Q2514                           [471526, 479132, 489844]    11000246.0
1    Q66286  [471554, 471574, 471612, 471651, 471680, 47168...    11002287.0
2   Q895636  [471532, 471825, 471980, 472676, 473851, 47411...    11002354.0
3    Q65389  [471527, 471596, 471692, 473651, 479473, 50886...    11000418.0
4  Q1594398  [471536, 471967, 472560, 473468, 473996, 47411...    11000891.0

In [363]:
test5.columns

Index(['politicianID', 'speeches', 'mapped_name', 'forename_lower_mapped',
       'surname_lower_mapped', 'surname_lower_comb', 'forename_lower_comb',
       'pageid', 'wikidataid', 'name', 'surname_lower', 'forename_lower'],
      dtype='object')

In [364]:
NamesAndSpeeches.columns

Index(['WikiIDs', 'speeches', 'politicianID'], dtype='object')

In [366]:
NamesAndSpeeches_full = pd.merge(NamesAndSpeeches, test5[['surname_lower_comb', 'forename_lower_comb',
       'pageid', 'wikidataid', 'name']], how = "left", left_on=["WikiIDs"], right_on=["wikidataid"])

In [367]:
NamesAndSpeeches_full.head()

,WikiIDs,speeches,politicianID,surname_lower_comb,forename_lower_comb,pageid,wikidataid,name
0,Q2514,"[471526, 479132, 489844]",11000246.0,brandt,willy,1518001.0,Q2514,Willy Brandt
1,Q66286,"[471554, 471574, 471612, 471651, 471680, 47168...",11002287.0,süssmuth,rita,4253.0,Q66286,Rita Süssmuth
2,Q66286,"[471554, 471574, 471612, 471651, 471680, 47168...",11002287.0,süssmuth,rita,4253.0,Q66286,Rita Süssmuth
3,Q66286,"[471554, 471574, 471612, 471651, 471680, 47168...",11002287.0,süssmuth,rita,4253.0,Q66286,Rita Süssmuth
4,Q66286,"[471554, 471574, 471612, 471651, 471680, 47168...",11002287.0,süssmuth,rita,4253.0,Q66286,Rita Süssmuth

In [397]:
NamesAndSpeeches_full_copy = NamesAndSpeeches_full.copy()

In [398]:
NamesAndSpeeches_full_copy["speeches"] = NamesAndSpeeches_full_copy["speeches"].map(lambda x: str(x))

In [399]:
NamesAndSpeeches_full_copy = NamesAndSpeeches_full_copy.drop_duplicates()

In [400]:
len(NamesAndSpeeches_full_copy)

2187

In [401]:
NamesAndSpeeches_full_copy = NamesAndSpeeches_full_copy.reset_index().drop(columns = ["WikiIDs", "index"])

In [402]:
NamesAndSpeeches_full_copy.head()

,speeches,politicianID,surname_lower_comb,forename_lower_comb,pageid,wikidataid,name
0,"[471526, 479132, 489844]",11000246.0,brandt,willy,1518001.0,Q2514,Willy Brandt
1,"[471554, 471574, 471612, 471651, 471680, 47168...",11002287.0,süssmuth,rita,4253.0,Q66286,Rita Süssmuth
2,"[471532, 471825, 471980, 472676, 473851, 47411...",11002354.0,ullmann,wolfgang,300219.0,Q895636,Wolfgang Ullmann
3,"[471527, 471596, 471692, 473651, 479473, 50886...",11000418.0,dregger,alfred,73446.0,Q65389,Alfred Dregger
4,"[471536, 471967, 472560, 473468, 473996, 47411...",11000891.0,heuer,uwe-jens,1097338.0,Q1594398,Uwe-Jens Heuer

In [404]:
NamesAndSpeeches_full_copy.to_csv(PATH + "processed/NamesAndSpeeches_full.csv")

In [709]:
from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

In [861]:
import Levenshtein as lev

Str1 = "Apple Inc."
Str2 = " Inc"

Distance = lev.distance(Str1.lower(),Str2.lower()),
print(Distance)

Ratio = lev.ratio(Str1.lower(),Str2.lower())

print(Ratio)

def similar_levenshtein(a, b):
    return lev.ratio(a.lower(),b.lower())

(6,)
0.5714285714285714

In [712]:
# correction of PolID2SpeechID_df


non_mached_names = ['jörg ganschow',
 ' gysi' ,
 'vera lengsfeld' ,
 'jürgen w möllemann',
 'irmgard schwaetzer',
 ' schmidt',
 'andrea gysi',
 'harald b schäfer',
 'gerhart rudolf baum',
 'margot renesse',
 'christina schenk',
 ' bläss',
 'joachim graf schönburg-glauchau',
 ' wimmer',
 ' schäfer',
 'peter w reuschenbach',
 'de maizi re',
 ' heimrich',
 'wolfgang stetten',
 'klein zur wahl des g- -gremiums',
 'ku an sagt',
 'tudjman sagt',
 'teichman logischen',
 'reinhard schorlemer',
 'heinrich l kolb',
 'kohl erklärt',
 ' stavenhagen',
 'lilo blunck',
 'susanne jaffke-witt',
 'kurt j rossmanith',
 ' blank',
 'hans with',
 'hans h gattermann',
 'joachim poss',
 'helmut kohl gen',
 'gerhard o pfeffermann',
 'michael schmude',
 'uta titze',
 'lutz g stavenhagen',
 'sabine bergmann-pohl parl',
 'ferdi tillmann',
 'gunter weissgerber',
 'peter patema',
 'klaus w lippold',
 'heinz werner hübner',
 'bush sagt sich',
 'dorle marx',
 'bitte schön roswitha verhülsdonk',
 'jörg essen',
 'herbert meissner',
 'erich g fritz',
 'erika steinbach',
 'rita süssmuth überweisungsvorschlag',
 'detlev larcher',
 'paul k friedhoff',
 'gisela hilbrecht',
 'rostock-laage hans georg wagner',
 'peter h carstensen',
 'werner h skowron',
 'christel riemann-hanewinckel',
 'alois graf waldburg-zeil',
 'barbara höii',
 'werner tegtmeier',
 'herr staatssekretär werner tegtmeier',
 'karl-hermann haack',
 'cornelia teichman',
 'brigitte schulte',
 'lothar maizi re',
 'rita süssmuth nennen',
 'r werner schuster',
 'lutz g stavenhagen',
 'kohl zum milliardenkredit lautet',
 'jetzt erklärt walter jens',
 'bitte herr staatsminister helmut schäfer',
 'herr staatsminister helmut schäfer',
 'staatsministerin seiler-albring ursula seiler-albring',
 'karl h fell',
 'kohl hat kürzlich ausgeführt',
 'ursula schmidt',
 'meine damen herren',
 'hans klein konzernabschlußbefreiungsverordnung',
 'franz kroppenstedt',
 ' dieter-julius-cronenberg',
 'staatsministerin bitte ursula seiler-albring',
 'gernot eder',
 'helmuth becker berichterstattung',
 'bertold reinartz',
 ' klaus-dieter-feige',
 'dieter-julius cronenberg berichterstattung',
 'erich maass',
 'bitte staatsministerin ursula seiler-albring',
 'bitte staatsminister ursula seiler-albring',
 'helmut kohl tatsache ist',
 'andreas bülow',
 'frerich görts',
 'rita süssmuth berichterstattung',
 ' hans-günthertoetemeyer',
 'hans schuster',
 'carl-detlev hammerstein',
 'reinhard meyer bentrup',
 'barbara hält',
 'wolfgang geldern',
 'renate schmidt berichterstattung',
 'kohl folgendes versprechen ab',
 'hans a engelhard',
 'hans klein berichterstattung',
 ' kreisky',
 'helmut kohl gestern erneut bekräftigte',
 'ulrich inner',
 'wolfgang gröbl part',
 'wolfgang gröbl parl',
 'hans klein überweisungsvorschlag',
 'joseph-todor blank',
 'fujimori gesagt',
 'frerich görts',
 'bitte herr staatsminister anton pfeifer',
 'bitte helmut schäfer',
 'hans klein tagesordnungspunkt',
 'cristian schmidt',
 'dieter würzen',
 'helmut schmidt hat einmal gesagt',
 'johannes vöcking',
 'wilhelm knittel',
 'helmut schmidt',
 'roosevelt hat einmal formuliert',
 'klein darauf hingewiesen',
 'walter priesnitz',
 'heinemann immer wieder mahnend vorhielten',
 'staatsminister ursula seiler-albring',
 'minister ursula seiler-albring',
 'staatsministerin ursula seiler-albring',
 'bitte herr staatsminister bernd schmidbauer',
 'walesa wie folgt formuliert hat',
 'helmut scholz',
 'helmuth becker überweisungsvorschlag',
 'baldur wagner',
 'kohl stellt fest',
 'renate schmidt überweisungsvorschlag',
 'peter bläss',
 'reante schmidt',
 'südkoreas fragte',
 'herr staatsminister bernd schmidbauer',
 'dieter-julius cronenberg überweisungsvorschlag',
 'kohl mehr noch',
 'wighard härdtl',
 'dietrich vogel',
 'franz-josef feiter',
 'wilhelm knittel',
 'bitte herr staatssekretär clemens stroetmann',
 'clemens stroetmann',
 'walesa es unumwunden ausgesprochen',
 'franz-josef feiter',
 'herr staatssekretär clemens stroetmann',
 'clemens stroetmann',
 'wighard härdtl',
 'hans klein rhythmus -',
 'bitte staatsministerire ursula seiler-albring',
 'gemot eder',
 'dieter-julius cronenberg tagesordnungspunkt k',
 'dieter vogel',
 'helmuth becker tagesordnungspunkt e',
 'bitte sehr helmut schäfer',
 'jelzin in seiner rede sagt',
 'hans klein der text lautet',
 'roman herzog',
 'roman herzog ländern',
 'ursula seiler-aibring',
 'hans klein tagesordnungspunkt m',
 'helmut kohl hat daran erinnert',
 'heinrich graf einsiedel',
 'joseph fischer',
 'marieluise beck',
 'kohl formulierte',
 'herr staatsminister werner hoyer',
 'norbert rängen',
 ' hans-ulrich',
 'eckart klaeden',
 'heidi wright',
 'antje vollmer berichterstattung',
 'havel zitieren',
 'havel hat folgendes erklärt',
 'hans-ulrich klose berichterstattung',
 'wolfgang llte',
 'dagmar g wöhrl',
 'frage des abgeordneten wolfgang steiger',
 'bitte franz-josef feiter',
 'manfred overhaus',
 'r manfred overhaus',
 'kohl zugeschickt',
 'hans-ulrich klose tagesordnungspunkt',
 'reagan gesagt',
 ' carl-ludwig',
 'karl jung',
 'chirac premierminister jupp einig',
 'antje vollmer überweisungsvorschlag',
 'petra blass',
 'hans-ulrich klose zusatzpunkt',
 'adelheid tröscher',
 'heinz dieter essmann',
 'gottfried trager',
 'karl jung',
 'wolfensohn u a',
 'antje vollmer tagesordnungspunkt',
 'jürgen stark',
 'bitte jürgen stark',
 'clinton hat recht gesagt',
 'izetbegovic gesagt hat ist richtig',
 'hans-ulrich klose überweisungsvorschlag',
 'bernd klaussner',
 'bitte werner hoyer',
 'helmut schmidt ablösten sagten sie',
 'hans klein tue ich hiermit',
 'bitte herr staatssekretär helmut schäfer',
 'burkhard hirsch richtigen',
 'antje vollmer sagt',
 'hans klein zusatzpunkt',
 'hans-friedrich ploetz',
 'bitte schön bernd schmidbauer',
 'karl a lamers',
 'hans-ulrich klose gesordnung folgendes mit',
 'hirsch hat mit recht gesagt',
 'kohl sagt',
 'herzog hingewiesen hat',
 'burkhard hirsch überweisungsvorschlag',
 'herr staatssekretär helmut schäfer',
 'bitte schön helmut schäfer',
 'peter hausmann',
 'walter hirrlinger fordert',
 'marielulse beck',
 'peter hausmann',
 'hans-ulrich klose wörtlich gesagt',
 'kiesinger vor dem hohen hause',
 'milosevi gerichtet',
 'mandela hat gesagt',
 'milo evi',
 'heinz-georg seifert',
 'bitte schön werner hoyer',
 'michaela geiger berichterstattung',
 'burkhard hirsch berichterstattung',
 'herzog stammt der satz',
 'bitte herr staatssekretär wilhelm hecker',
 'wilhelm hecker',
 'herr staatssekretär wilhelm hecker',
 'herr staatsminister bitte helmut schäfer',
 'michaela geiger tagesordnungspunkt a',
 'herzog in straßburg gesagt hat',
 'michaela geiger zusatzpunkt',
 ' carl-ludwig-thiele',
 'hans-ulrich klose gestimmt',
 'hans-ulrich klose tagesordnungspunkt u',
 'helmut kohl erstens',
 'herzog geprägt hat',
 'hans-ulrich klose abgegebene stimmen',
 'burkhard hirsch zusatzpunkt',
 'jelzin sagte ihm',
 'christa thoben',
 'michaela geiger überweisungsvorschlag',
 'milosevic muß wissen',
 'herzog gesagt hat',
 'herzog es meinte',
 'willi hausmann',
 'antje vollmer zusatzpunkt',
 'hans-ulrich klose tagesordnungspunkt i',
 'hans-ulrich klose tagesordnungspunkt q',
 'hans-ulrich klose tagesordnungspunkt o',
 'hans-ulrich klose tagesordnungspunkt x',
 'hans-ulrich klose zusatzpunkt a',
 'bodo hombach',
 'werner müller',
 'karl-heinz funke',
 'christine bergmann',
 'willy brandt gesagt',
 'schröder weiter steht da',
 'klaus wolfgang müller',
 'wolfgang gehrcke-reymann',
 'ulla lötzer',
 'kohl nicht gegeben hätte',
 'schröder der bundeskanzler weiter',
 'ernst ulrich weizsäcker',
 'axel e fischer',
 'michael naumann',
 'klima sagt',
 'schröder übrigens',
 'ahtisaari die nachricht aus belgrad',
 'karl lamers -karl lamers',
 'schröder auf',
 'schröder gesagt',
 'schröder klar sein',
 'annette fugmann-heesing',
 'roland koch',
 'johannes rau',
 'schröder sagen',
 'hoover erklärte',
 'eckart werthebach',
 'ren röspel',
 'uwe-karsten heye',
 'reinhard klimmt',
 'vizepräsidentin petra bläss',
 'gespräche über die frage',
 'schröder hätte ihnen gesagt',
 'cajus caesar',
 'kollegin - rita streb-hesse',
 'rainer baake',
 'schröder in dem er mitteilt',
 'hirrlinger sagt dazu',
 ' christaluft',
 'grietje staffelt',
 'christoph stölzl',
 'willfried maier',
 'hartmuth wrocklage',
 'achim großmann parl staatssekretär beim bundesminister für verkehr bau- wohnungswesen',
 'erich stather',
 'peter haupt',
 'johannes rau schließen',
 'ihnen gesagt hätte',
 'schröder bekräftigt hat',
 'schröder in seiner regierungserklärung ausgeführt',
 ' santer',
 'erwin anton jordan',
 'schröder führte weiter aus',
 'julian nida-rümelin',
 'gerhard schröder gesagt',
 'gunter pleuger',
 'schröder wort gemeldet hat',
 'herr staatssekretär erich stather',
 'schröder knallhart gesagt',
 'peter kurth',
 'schröder hat recht',
 'mosdorf oder so wie jetzt',
 'rau hat gesagt',
 'bush sagte sie',
 ' hundt',
 'kohl dort heißt es',
 'ebtekar - deutlich geworden',
 'herr möllemann ist - steht',
 'schröder gesagt hat',
 'bush hat darüber gesprochen',
 'theodor heuss als er sagte',
 'helmut schmidt hat gesagt',
 'thomas flierl',
 'schröder gilt',
 'ronald b schill',
 'kohl sagte',
 'manfred stolpe',
 'wolfgang clement',
 'schröder vollmundig aufgestellte forderung',
 'silke stokar neuforn',
 'christina weiss',
 'helmut schmidt hat völlig recht',
 'cornelia mayer',
 'christian stetten',
 'dorothee bär',
 'karl-theodor guttenberg',
 'karzai hat uns gesagt',
 'b la anda',
 'spd-mitglied roland schäfer',
 'chirac hat immer gesagt',
 'josef philip winkler',
 'wolfgang thierse berichterstattung',
 'schröder unter anderem erklärt',
 ' bundeskanzleramtes',
 'hermann otto solms überweisungsvorschlag',
 'klaus werner jonas',
 'b la anda',
 'wolfgang thierse überweisungsvorschlag',
 'gerhard schröder zentrale aussage war',
 'schröder äußerte sich dazu wörtlich',
 'braun hat gestern gesagt',
 'wolfgang böhmer',
 'schröder übrigens seinem vorgänger',
 'schröder verkündet dazu',
 'roger kusch',
 'hermann otto solms berichterstattung',
 'professor hans-jörg jacobsen',
 'ist das richtig kerstin müller',
 ' deutschland',
 'hermann otto solms landwirtschaft',
 'norbert lammert berichterstattung',
 'harald wolf',
 'elvira drobinski-weiss',
 'dieter althaus',
 'professor horst köhler',
 'gerhard schröder erwarten',
 'recht hat',
 'bush nimmt',
 'kiesinger in einer regierungserklärung',
 'herr koch-weser',
 'eisenhower hat gesagt',
 'schröder dem bosnischen ministerpräsidenten mitgeteilt',
 'schröder wortwörtlich geantwortet',
 'schröder soll geantwortet haben',
 'schüssel erklärt mit stolz',
 'staatsministerin christina weiss',
 'köhler sagen',
 'aus verantwortung für unser land',
 'ziercke sagte in demselben interview',
 'thumann hat festgestellt',
 'israel besuchte sagte damals',
 'schröder nur empfehlen',
 'carl-eduard bismarck',
 'sie gefragt hat',
 'köhler zitieren',
 'ursula der leyen',
 'thomas maizi re',
 'vizepräsident wolfgang thierse',
 'wolfgang neskovic',
 'merkel -',
 'doroth e menzner',
 'recht geben',
 'sevim da delen',
 'heidrun bluhm-förster',
 'gerhard schröder hatte gesagt',
 'hakki keskin',
 'heuss hat einmal gesagt',
 'angela merkel zitieren',
 'max lehmer',
 'gerda hasselfeldt überweisungsvorschlag',
 'herr lämmel - andreas g lämmel',
 'edmund peter geisen',
 'schröder der sagt',
 'philipp missfelder',
 'bernd neumann die folgende antwort',
 'katrin göring-eckardt tagesordnungspunkt b',
 'merkel gesagt hat',
 'schröder schon früher sagte',
 'wolfgang ne kovi',
 'klaus böger',
 'norbert lammert überweisungsvorschlag',
 'mbeki sagt',
 'petra pau tagesordnungspunkt',
 'merkel hat gesagt',
 'angela merkel sagen',
 'katrin göring-eckardt überweisungsvorschlag',
 'katrin göring-eckardt tagesordnungspunkt f',
 'hien auf nachfrage',
 'gerda hasselfeldt tagesordnungspunkt e',
 'angela merkel enthalten',
 'gerda hasselfeldt tagesordnungspunkt i',
 'inhalt der gesetzesänderungen ist',
 'katrin lompscher',
 'hans bernhard beus',
 'horst köhler schließen',
 'gerda hasselfeldt tagesordnungspunkt d',
 'gerda hasselfeldt tagesordnungspunkt j',
 'putin gerichtet sage ich',
 'bitte gernot erler',
 'norbert lammert überwiesen',
 'hüseyin-kenan aydin bundespräsident herzog',
 'herzog bundeskanzler kohl außenminister fischer',
 'katrin göring-eckardt tagesordnungspunkt k',
 'katrin göring-eckardt zusatzpunkt',
 'katrin göring-eckardt berichterstattung',
 'angela merkel ich sage',
 'bush in tirana erklärt hat',
 'katrin göring-eckardt tagesordnungspunkt o',
 'merkel sagte am november',
 'gerda hasselfeldt tagesordnungspunkt',
 'gerda hasselfeldt tagesordnungspunkt b',
 'petra pau überweisungsvorschlag',
 'heuss formuliert',
 'petra pau tagesordnungspunkt g',
 'gerda hasselfeldt tagesordnungspunkt l',
 'gerda hasselfeldt zusatzpunkt d',
 'horst köhler sagte vor kurzem',
 ' frauen',
 'petra pau berichterstattung',
 'frieder meyer-krahmer',
 'kabila wurde die devise ausgegeben',
 'gerda hasselfeldt berichterstattung',
 'angela merkel danken',
 'petra pau tagesordnungspunkt i',
 'katrin göring-eckardt tagesordnungspunkt l',
 'bundesregierung vor einigen monaten gesetzt',
 'katrin göring-eckardt tagesordnungspunkt',
 'petra pau zusatzpunkt',
 'merkel vor kurzem erklärt',
 'katrin göring-eckardt tagesordnungspunkt d',
 'herr staatsminister bitte hermann gröhe',
 'köhler hat zur finanzkrise gesagt',
 'gerda hasselfeldt tagesordnungspunkt u',
 'gerda hasselfeldt grünbuch ten-v',
 'gerda hasselfeldt tagesordnungspunkt mm',
 'gerda hasselfeldt zusatzpunkt m',
 'gerda hasselfeldt zusatzpunkt w',
 'lammert sagte vor wenigen monaten',
 'philipp rösler',
 'jan aken',
 'eckart klaeden',
 'konstantin notz',
 'memet kilic',
 'matthias w birkwald',
 'hermann e ott',
 'obama hat drei elemente benannt',
 'gerda hasselfeldt kollegen oppermann bekannt',
 'gabriele molitor',
 'gerda hasselfeldt zusatzpunkt',
 'petra pau tagesordnungspunkt e',
 'lisa paus',
 'bitte staatsministerin cornelia pieper',
 'viola cramon-taubadel',
 'johann david wadephul',
 'patrick sensburg',
 'jean-claude trichet formulierte es so',
 'hans-georg der marwitz',
 'aydan özo uz',
 'angela merkel passiert ist',
 'was haben ministerpräsidenten',
 'sonja amalie steffen',
 'bitte cornelia pieper',
 'merkel gesagt',
 'herr kampeter',
 'jens böhrnsen',
 'christian wulff',
 'pieper bitte cornelia pieper',
 'merkel die bildungsrepublik ausgerufen frage',
 'schröder festgestellt',
 'sarkozy drei vorstellungen',
 'abgeordneten fraktionen ist',
 'august hanning',
 'jürgen zöllner',
 'herr staatssekretär werner hoyer',
 'kohl der gesagt hat',
 'eduard oswald berichterstattung',
 'eduard oswald überweisungsvorschlag',
 'eduard oswald tagesordnungspunkt',
 'abschließen möchte ich mit einem zitat des rheinland-pfälzischen infrastrukturministers roger lewenz',
 'dazu hat der kollege stadler',
 'südafrikas hat einmal gesagt',
 'eduard oswald halber frage ich',
 'zeit gelassen',
 'obama gesagt hat war',
 'pieper bereit cornelia pieper',
 'eduard oswald tagesordnungspunkt g',
 'merkel sagen',
 'michael link',
 'angela merkel daraus folgt',
 'jörg polheim',
 'joachim gauck',
 'hans-jürgen beerfeltz',
 'bundesministerium der finanzen',
 'bundesministerium für arbeit soziales',
 'horst köhler sagte',
 'merkel haben gesagt',
 'merkel hier auf',
 'merkel hier hingestellt gesagt',
 'detlef scheele',
 'johanna wanka',
 'schröder einmal skizziert',
 'cornelia prüfer-storcks',
 'ronald reagan',
 'gauck der gesagt hat',
 'dieter hundt hat ausgeführt',
 'grillo hat des weiteren gesagt',
 'eduard oswald tagesordnungspunkt s',
 'katrin göring-eckardt tagesordnungspunkt cc',
 'katrin göring-eckardt tagesordnungspunkt yy',
 'pia zimmermann',
 'alexander s neu',
 'johanna wanka',
 'manuela schwesig',
 'ja thomas maizi re',
 'andr hahn',
 'johannes singhammer überweisungsvorschlag',
 'angela merkel damals sagte',
 'charles m huber',
 'ulle schauws',
 'peter hintze tagesordnungspunkt b',
 'peter hintze tagesordnungspunkt',
 'michaela engelmeier',
 'staatsministerin maria böhmer',
 'philipp graf lerchenfeld',
 'elisabeth motschmann',
 'volker ullrich',
 ' janukowitsch',
 'gauck geschrieben hat sie schrieb',
 'petra pau tagesordnungspunkt b',
 'edelgard bulmahn überweisungsvorschlag',
 'sylvia jörrissen',
 'kees vries',
 'matern marschall',
 'alois rainer',
 'joachim gauck diese zeilen',
 'gauck zitieren',
 'ulla schmidt überweisungsvorschlag',
 'bitte herr staatsminister michael roth',
 'andr berghegger',
 'christina jantz-herrmann',
 'edelgard bulmahn tagesordnungspunkt',
 'joachim gauck als er sagte',
 ' putin',
 'jochim pfeiffer',
 ' drobinski-weiß',
 'abstimmung über den einzelplan',
 'peter hintze tagesordnungspunkt f',
 'peter hintze tagesordnungspunkt l',
 'barsani hat mir gesagt',
 'herr staatssekretär bitte klaus-dieter fritsche',
 'klaus-dieter fritsche',
 'herr staatsminister bitte michael roth',
 'herr staatsminister michael roth',
 'gauck hat es treffend formuliert',
 'jutta blankau-rosenfeldt',
 'claudia roth überweisungsvorschlag',
 'edelgard bulmahn tagesordnungspunkt iv e',
 'edelgard bulmahn drucksache überweisungsvorschlag',
 'obama unter freunden',
 'putin aussehen muss man sagen',
 'claudia roth schließungsantrag ist abgelehnt',
 'ulla schmidt tagesordnungspunkt',
 'danke michael roth',
 'peter hintze überweisungsvorschlag',
 'claudia roth tagesordnungspunkt b',
 'agenda zurückdrängen',
 'claudia roth zusatzpunkt d',
 'ulla schmidt drucksache überweisungsvorschlag',
 'obama doch einmal eins erklären',
 'ulla schmidt zusatzpunkt',
 'johannes singhammer tagesordnungspunkt i',
 ' entscheidungen',
 'putin war',
 'willy brandt abschließen',
 ' herausforderung',
 'erdogan seiner politik gilt',
 'frankreichs hat gesagt',
 'herr dobrindt',
 'putin gegenüber deutlich gemacht -',
 'ankündigungsprogramm bleibt',
 'malu dreyer',
 'lammert ich erinnere mich noch',
 'helmut schmidt formulierte das so',
 'claudia roth https',
 'merkel die heute sagte',
 'joachim gauck gesagt hat',
 'petra pau zusatzpunkt f',
 'eva-maria schreiber',
 'elvan korkmaz-emre',
 'bettina margarethe wiesmann',
 'franziska giffey',
 'svenja schulze',
 'helin evrim sommer',
 'thomas opperman',
 'norbert maria altenkamp',
 'britta katharina dassler',
 'andreas geisel',
 'nezahat baradari',
 'gerhard zickenheiner',
 'peter heidt',
 'isabel mackensen',
 'elke breitenbach',
 'sandra bubendorfer-licht',
 'joe weingarten',
 'sylvia lehmann',
 'bela bach',
 'matthias nölke',
 'charlotte schneidewind-hartnagel',
 'dorothee martin',
 'saskia ludwig',
 'janosch dahmen',
 'christian natterer',
 'christopher gohl',
 'maika friemann-jennert']

In [735]:
wikipedia_names = ID_and_names_from_Wiki["name"]

In [715]:
similar(non_mached_names[1], "hallo")

0.0

In [716]:
non_mached_names[1]

' gysi'

In [718]:
similar(non_mached_names[1], "gregor gysi")

0.625

In [724]:
similar(non_mached_names[1], "andrea gysi")

0.625

In [736]:
def find_most_similiar_name(minutes_name): 
    minutes_name = minutes_name.lower()

    scores = []

    for name in wikipedia_names: 
        scores.append(similar(name, minutes_name))

    index_of_interest = scores.index(max(scores))

    return wikipedia_names[index_of_interest]

In [871]:
def find_most_similiar_name_levenshtein(minutes_name): 
    minutes_name = minutes_name.lower()

    scores = []

    for name in wikipedia_names: 
        scores.append(similar_levenshtein(name, minutes_name))

    index_of_interest = scores.index(max(scores))
    
    if max(scores) >= 0.65:
        res = wikipedia_names[index_of_interest]
        
    else: 
        res = np.nan
    
    return res

In [737]:
max(scores)

0.6511627906976745

In [738]:
scores.index(max(scores))

248

In [739]:
non_mached_names[scores.index(max(scores))]

'hans-ulrich klose gestimmt'

In [744]:
find_most_similiar_name(" gysi")

'Gregor Gysi'